var gac="Abu Dhabi (United Arab Emirates : Emirate)\n  USE  Abu Z.aby (United Arab Emirates : Emirate)@"
+"Abu Z.aby (United Arab Emirates : Emirate)\n  Assigned code:\n     a-ts --- United Arab Emirates@"
+"Abyssinia\n  USE  Ethiopia@"
+"Adamawa (Emirate)\n  Assigned codes:\n     f-cm --- Cameroon\n     f-nr --- Nigeria@"
+"Aden (Protectorate)\n     Coded a-ys (Yemen (People's Democratic Republic) before Oct. 1992 \n  Assigned code:\n     a-ye --- Yemen@"
+"Aden, Gulf of\n  Assigned code:\n     mr --- Red Sea@"
+"Aden\n     Coded a-ys (Yemen (People's Democratic Republic) before Oct. 1992 \n  Assigned code:\n     a-ye --- Yemen@"
+"Admiralty Islands (Papua New Guinea)\n  Assigned code:\n     a-pp --- Papua New Guinea@"
+"Adriatic Sea\n  Assigned code:\n     mm --- Mediterranean Sea@"
+"Aegean Islands (Greece and Turkey)\n  Assigned codes:\n     e-gr --- \n     a-tu --- Turkey@"
+"Aegean Sea\n  Assigned codes:\n     e-gr --- \n     a-tu --- Turkey@"
+"Afars and Issas, French Territory of the\n  USE  Djibouti@"
+"Afghanistan --- a-af@"
+"Africa --- f@"
+"Africa, Central --- fc@"
+"Africa, East\n  Assigned code:\n     fe --- Africa, Eastern@"
+"Africa, Eastern --- fe@"
+"Africa, Equatorial\n  USE  Africa, French-speaking Equatorial@"
+"Africa, French-speaking Equatorial --- fq@"
+"Africa, French-speaking West\n  Assigned code:\n     fw --- Africa, West@"
+"Africa, Italian East\n  USE  Africa, Northeast@"
+"Africa, North --- ff@"
+"Africa, Northeast --- fh@"
+"Africa, Northwest\n  Assigned codes:\n     ff --- Africa, North\n     fw --- Africa, West@"
+"Africa, South\n  USE  South Africa@"
+"Africa, Southern --- fs@"
+"Africa, Southwest\n  USE  Namibia@"
+"Africa, Sub-Saharan --- fb@"
+"Africa, West --- fw@"
+"Alabama --- n-us-al@"
+"Alaska --- n-us-ak@"
+"Alaska, Gulf of (Alaska)\n  Assigned code:\n     pn --- North Pacific Ocean@"
+"Albania --- e-aa@"
+"Alberta --- n-cn-ab@"
+"Alderney\n  Assigned code:\n     e-uk-ui --- Great Britain Miscellaneous Island Dependencies@"
+"Algeria --- f-ae@"
+"Alps --- ea@"
+"Amazon River --- sa@"
+"America, Central\n  USE  Central America@"
+"America\n  Assigned codes:\n     n --- North America\n     s --- South America@"
+"American Samoa --- poas@"
+"Amur River (China and Russia) --- aa@"
+"Andaman and Nicobar Islands (India)\n  Assigned code:\n     a-ii --- India@"
+"Andean Area\n  USE  Andes@"
+"Andes --- sn@"
+"Andorra --- e-an@"
+"Anglo-Egyptian Sudan\n  USE  Sudan@"
+"Angola --- f-ao@"
+"Anguilla --- nwxa\n     Coded nwxi (Saint Kitts and Nevis) before Mar. 1988@"
+"Anhwei Province (China) --- a-cc-an@"
+"Antarctic Ocean --- t@"
+"Antarctic regions \n  USE  Antarctica@"
+"Antarctica --- t\n     Coded also t-ay (Antarctica) before Mar. 1988@"
+"Antigua and Barbuda --- nwaq@"
+"Antigua\n  Assigned code:\n     nwaq --- Antigua and Barbuda@"
+"Antilles, Greater\n     Coded nwga (Greater Antilles) before Mar. 1988\n  USE  West Indies@"
+"Antilles, Lesser --- nwla@"
+"Appalachian Mountains --- n-usa@"
+"Appalachian Mountains, Southern\n  Assigned code:\n     n-usa --- Appalachian Mountains@"
+"Appalachian Region\n  Assigned code:\n     n-usa --- Appalachian Mountains@"
+"Aqaba, Gulf of\n  Assigned code:\n     mr --- Red Sea@"
+"Arab Republic of Yemen\n  USE  Yemen@"
+"Arab countries --- ma@"
+"Arabia, Southern\n  Assigned codes:\n     a-mk --- Oman\n     a-ye --- Yemen@"
+"Arabia\n  USE  Arabian Peninsula@"
+"Arabian Peninsula --- ar@"
+"Arabian Sea --- au@"
+"Arabic countries\n  USE  Arab countries@"
+"Arafura Sea\n  Assigned code:\n     ps --- South Pacific Ocean@"
+"Aran Islands (Ireland)\n  Assigned code:\n     e-ie --- Ireland@"
+"Archipel des Marquises (French Polynesia)\n  USE  Marquesas Islands (French Polynesia)@"
+"Arctic Ocean --- r@"
+"Arctic regions --- r@"
+"Argentina --- s-ag@"
+"Arizona --- n-us-az@"
+"Arkansas --- n-us-ar@"
+"Armenia (Republic) --- a-ai\n     Coded e-ur-ai (Armenia (Republic)) before June 1998@"
+"Armenia\n  Assigned codes:\n     a-ai --- Armenia (Republic)\n     a-ir --- Iran\n     a-tu --- Turkey@"
+"Armenian S.S.R.\n  USE  Armenia (Republic)@"
+"Aruba\n  Assigned code:\n     nwco --- Curaçao@"
+"Ascension Island (Atlantic Ocean) --- lsai@"
+"Ashanti\n  USE  Ghana@"
+"Ashmore and Cartier Islands --- u-ac@"
+"Asia --- a@"
+"Asia Minor\n  USE  Turkey@"
+"Asia and Europe (treated collectively)\n  USE  Eurasia@"
+"Asia, Central --- ac@"
+"Asia, East\n  USE  East Asia@"
+"Asia, South --- az@"
+"Asia, Southeastern --- as@"
+"Asia, Southwestern\n  USE  Middle East@"
+"Asia, Western\n  USE  Middle East@"
+"Atlantic Coast (U.S.)\n  Assigned code:\n     n-us --- United States@"
+"Atlantic Ocean --- l@"
+"Atlantic States, South\n  USE  South Atlantic States@"
+"Atlantic States\n  Assigned code:\n     n-us --- United States@"
+"Atlas Mountains --- fa@"
+"Austral Islands (French Polynesia)\n  Assigned code:\n     pofp --- French Polynesia@"
+"Australasia --- u@"
+"Australia --- u-at@"
+"Australian Capital Territory --- aca@"
+"Austria --- e-au@"
+"Azad Jammu and Kashmir\n  USE  Azad Kashmir@"
+"Azad Kashmir\n  Assigned code:\n     a-pk --- Pakistan@"
+"Azerbaijan  --- a-aj\n     Coded e-ur-aj (Azerbaijan) before June 1998@"
+"Azerbaijan S.S.R.\n  USE  Azerbaijan@"
+"Azores --- lnaz@"
+"Açores\n  USE  Azores@"
+"Babylonia\n  Assigned code:\n     a-iq --- Iraq@"
+"Bahamas --- nwbf@"
+"Bahrain --- a-ba@"
+"Bahrein\n  USE  Bahrain@"
+"Balearic Islands (Spain)\n  Assigned code:\n     e-sp --- Spain@"
+"Balkan Peninsula --- ed@"
+"Baltic Sea\n  Assigned code:\n     ln --- North Atlantic Ocean@"
+"Baltic States --- eb@"
+"Banaba (Kiribati)\n  Assigned code:\n     pokb --- Kiribati@"
+"Bangladesh --- a-bg@"
+"Banks Islands (Vanuatu)\n  Assigned code:\n     ponn --- Vanuatu@"
+"Barbados --- nwbb@"
+"Barbuda\n     Coded nwbc (Barbuda) before Mar. 1988\n  Assigned code:\n     nwaq --- Antigua and Barbuda@"
+"Barents Sea\n  Assigned code:\n     r --- Arctic Ocean@"
+"Basutoland\n  USE  Lesotho@"
+"Bay of Bengal\n  USE  Bengal, Bay of@"
+"Bay of Fundy\n  USE  Fundy, Bay of@"
+"Bear Island (Norway)\n  Assigned code:\n     lnsb --- Svalbard (Norway)@"
+"Beaufort Sea\n  Assigned code:\n     r --- Arctic Ocean@"
+"Bechuanaland\n  USE  Botswana@"
+"Beijing (China)\n  USE  Peking (China)@"
+"Belarus --- e-bw\n     Coded e-ur-bw (Belarus) before June 1998@"
+"Belau\n  USE  Palau@"
+"Belgian Congo\n  USE  Congo (Democratic Republic)@"
+"Belgium --- e-be@"
+"Belize --- ncbh@"
+"Belorussian S.S.R.\n  USE  Belarus@"
+"Benelux countries --- el@"
+"Bengal, Bay of --- ab@"
+"Benin --- f-dm@"
+"Bering Sea\n  Assigned code:\n     pn --- North Pacific Ocean@"
+"Berlin (Germany)\n     Coded e-gx (Germany) for Berlin as a whole; e-ge (Germany (East)) for East Berlin; or e-gw (Germany (West)) for West Berlin before Jan. 1991 \n  Assigned code:\n     e-gx --- Germany@"
+"Bermuda Islands --- lnbm@"
+"Bermuda Triangle\n  Assigned code:\n     ln --- North Atlantic Ocean@"
+"Bhutan --- a-bt@"
+"Biafra\n     Coded f-by (Biafra) before Mar. 1988\n  Assigned code:\n     f-nr --- Nigeria@"
+"Bikini Atoll (Marshall Islands)\n  Assigned code:\n     poxe --- Marshall Islands@"
+"Bioco (Equatorial Guinea)\n  USE  Fernando Po (Equatorial Guinea)@"
+"Bioko (Equatorial Guinea)\n  USE  Fernando Po (Equatorial Guinea)@"
+"Bismarck Archipelago (Papua New Guinea)\n  Assigned code:\n     a-pp --- Papua New Guinea@"
+"Bjørnøya (Norway)\n  USE  Bear Island (Norway)@"
+"Black Sea --- mb@"
+"Blue Ridge Mountains\n  Assigned code:\n     n-usa --- Appalachian Mountains@"
+"Bo Hai (China)\n  USE  Po Hai (China)@"
+"Bohai (China)\n  USE  Po Hai (China)@"
+"Bolivia --- s-bo@"
+"Bonaire\n  Assigned code:\n     nwco --- Curaçao@"
+"Bophuthatswana (South Africa)\n  Assigned code:\n     f-sa --- South Africa@"
+"Borneo --- a-bn@"
+"Bosnia and Hercegovina --- e-bn@"
+"Botswana --- f-bs@"
+"Bougainville Island (Papua New Guinea)\n  Assigned code:\n     a-pp --- Papua New Guinea@"
+"Bouvet Island --- lsbv@"
+"Brazil --- s-bl@"
+"Brazzaville\n  USE  Congo (Brazzaville)@"
+"British Columbia --- n-cn-bc@"
+"British Commonwealth countries\n  USE  Commonwealth countries@"
+"British Dominions\n  USE  Commonwealth countries@"
+"British East Africa\n  USE  Africa, East@"
+"British Guiana\n  USE  Guyana@"
+"British Honduras\n  USE  Belize@"
+"British Indian Ocean Territory --- i-bi@"
+"British Isles\n  Assigned codes:\n     e-uk --- Great Britain\n     e-ie --- Ireland@"
+"British North Borneo\n  USE  Sabah@"
+"British Solomon Islands\n  USE  Solomon Islands@"
+"British Somaliland\n  USE  Somalia@"
+"British Togoland\n  USE  Togoland (British)@"
+"British Virgin Islands --- nwvb@"
+"British West Africa\n  USE  Africa, West@"
+"Brownsea Island (England)\n  Assigned code:\n     e-uk-en --- England@"
+"Brunei --- a-bx@"
+"Bulgaria --- e-bu@"
+"Burkina Faso --- f-uv@"
+"Burma --- a-br@"
+"Burundi --- f-bd@"
+"Byelorussian S.S.R. \n  USE  Belarus@"
+"Byzantine Empire\n  Assigned code:\n     mm --- Mediterranean Region@"
+"Cabo Verde\n  USE  Cape Verde@"
+"Caicos Islands\n  USE  Turks and Caicos Islands@"
+"Calf of Man\n  Assigned code:\n     e-uk-ui --- Great Britain Miscellaneous Island Dependencies@"
+"California --- n-us-ca@"
+"Cambodia --- a-cb@"
+"Cameroon --- f-cm@"
+"Cameroons, French\n  USE  Cameroon@"
+"Cameroons, Southern\n  USE  Cameroon@"
+"Cameroun\n  USE  Cameroon@"
+"Canada --- n-cn@"
+"Canada, Eastern\n  Assigned code:\n     n-cn --- Canada@"
+"Canada, Northern\n  Assigned code:\n     n-cn --- Canada@"
+"Canada, Western\n  Assigned codes:\n     n-cn-bc --- British Columbia\n     n-cnp --- Prairie Provinces@"
+"Canadian Northwest\n  USE  Northwest, Canadian@"
+"Canal Zone --- nccz@"
+"Canary Islands --- lnca@"
+"Canton and Enderbury Islands\n     Coded pocp (Canton and Enderbury Islands) before Mar. 1988\n  Assigned code:\n     pokb --- Kiribati@"
+"Cape Verde --- lncv@"
+"Caribbean Area --- cc@"
+"Caribbean Island Dependencies of the United States\n  USE  United States Miscellaneous Caribbean Islands@"
+"Caribbean Sea --- cc@"
+"Caribbean Sea Region\n  USE  Caribbean Area@"
+"Caroline Islands --- poci@"
+"Carpathian Mountains\n  Assigned code:\n     ee --- Europe, Eastern@"
+"Carpentaria, Gulf of (N.T. and Qld.)\n     Coded ps (South Pacific Ocean) before June 1998\n  Assigned code:\n     u-at-no --- Northern Territory\n     u-at-qn --- Queensland@"
+"Caspian Sea --- ak@"
+"Caucasus --- e-urk@"
+"Caucasus, Northern (Russia) --- e-urr@"
+"Cayman Islands --- nwcj@"
+"Celebes (Indonesia)\n  Assigned code:\n     a-io --- Indonesia@"
+"Central Africa\n  USE  Africa, Central@"
+"Central African Empire\n  USE  Central African Republic@"
+"Central African Republic --- f-cx@"
+"Central America --- nc@"
+"Central Asia\n  USE  Asia, Central@"
+"Central Black Earth Region (Russia)\n  USE  Central Chernozem Region (Russia)@"
+"Central Black Soil Region (Russia)\n  USE  Central Chernozem Region (Russia)@"
+"Central Chernozem Region (Russia) --- e-urc@"
+"Central Europe --- ec@"
+"Ceuta (Spain)\n  Assigned code:\n     f-sh --- Spanish North Africa@"
+"Ceylon\n  USE  Sri Lanka@"
+"Ch'ang Chiang (China)\n  USE  Yangtze River (China)@"
+"Chad --- f-cd@"
+"Chad, Lake\n  Assigned code:\n     fq --- Africa, French-speaking Equatorial@"
+"Chagos Islands\n  USE  British Indian Ocean Territory@"
+"Channel Islands\n  Assigned code:\n     e-uk-ui  --- Great Britain Miscellaneous Island Dependencies@"
+"Chekiang Province (China) --- a-cc-ch@"
+"Chesapeake Bay (Md. and Va.)\n  Assigned codes:\n     n-us-md --- Maryland\n     n-us-va --- Virginia@"
+"Chihli, Gulf of (China)\n  USE  Po Hai (China)@"
+"Chile --- s-cl@"
+"China --- a-cc@"
+"Chishima-retto (Russia)\n  USE  Kuril Islands (Russia)@"
+"Chongqing (China) --- a-cc-cq\n     [Previously coded [a-cc-sz] (Szechuan Province (China)) before Sept. 2000]@"
+"Christmas Island (Indian Ocean) --- i-xa@"
+"Christmas Island (Pacific Ocean)\n  USE  Kiritimati (Kiribati)@"
+"Circumcaribbean\n     Coded cr (Circumcaribbean) before Mar. 1988\n  USE  Caribbean Area@"
+"Cocos (Keeling) Islands --- i-xb@"
+"Cold regions --- q@"
+"Colombia --- s-ck@"
+"Colorado --- n-us-co@"
+"Colorado River (Colo.-Mexico)\n  Assigned codes:\n     n-mx --- Mexico\n     n-usp  --- West (U.S.)@"
+"Colorado River Delta (Mexico)\n  Assigned code:\n     n-mx --- Mexico@"
+"Columbia River\n  Assigned code:\n     n-usp  --- West (U.S.)@"
+"Commonwealth countries --- b@"
+"Commonwealth nations\n  USE  Commonwealth countries@"
+"Commonwealth of Independent States countries\n  USE  Soviet Union@"
+"Commonwealth of the Northern Mariana Islands\n  USE  Mariana Islands@"
+"Communaute francaise\n  USE  French Community@"
+"Communist countries --- v\n     Coded v (Communist countries) before June 1998\n  Assigned codes:\n     e-ur --- Soviet Union\n     ee  --- Europe, Eastern@"
+"Comoro Islands\n  USE  Comoros@"
+"Comoros --- i-cq@"
+"Confederate States of America\n  Assigned code:\n     n-usu --- Southern States@"
+"Congo (Brazzaville) --- f-cf@"
+"Congo (Democratic Republic) --- f-cg@"
+"Congo (Kingdom)\n  USE  Kongo Kingdom@"
+"Congo (Kinshasa)\n  USE  Congo (Democratic Republic)@"
+"Congo (Leopoldville)\n  USE  Congo (Democratic Republic)@"
+"Congo River --- fg@"
+"Connecticut --- n-us-ct@"
+"Cook Islands --- pocw@"
+"Corsica (France)\n  Assigned code:\n     e-fr --- France@"
+"Costa Rica --- nccr@"
+"Crete (Greece)\n  Assigned code:\n     e-gr --- Greece@"
+"Croatia --- e-ci\n     Coded e-yu (Yugoslavia) before Oct. 1992@"
+"Cuba --- nwcu@"
+"Cumberland Mountains\n  Assigned code:\n     n-usu --- Southern States@"
+"Curaçao --- nwco@"
+"Cyprus --- a-cy@"
+"Czech Republic --- e-xr\n     Coded e-cs (Czechoslovakia) before May 1993@"
+"Czech Socialist Republic (Czechoslovakia)\n  USE  Czech Republic@"
+"Czechoslovakia --- e-cs\n     Includes the Czech Republic and Slovakia treated collectively@"
+"Côte d'Ivoire --- f-iv@"
+"D'Entrecasteaux Islands (Papua New Guinea)\n  Assigned code:\n     a-pp --- Papua New Guinea@"
+"Dahomey\n  USE  Benin@"
+"Danube River --- eo@"
+"Deep space --- x@"
+"Delaware --- n-us-de@"
+"Democratic German Republic\n  USE  Germany (East)@"
+"Denmark --- e-dk@"
+"Deep space --- zd@"
+"Desolation Islands\n  USE  Kerguelen Islands@"
+"Developed countries --- dd@"
+"Developing countries --- d@"
+"Diego Garcia\n  Assigned code:\n     i-bi --- British Indian Ocean Territory@"
+"District of Columbia\n  USE  Washington (D.C.)@"
+"Djibouti --- f-ft@"
+"Dodecanese (Greece)\n  USE  D¸dekan-sos (Greece)@"
+"Dominica --- nwdq@"
+"Dominican Republic --- nwdr@"
+"Dubai\n  USE  Dubayy (United Arab Emirates : Emirate)@"
+"Dubayy (United Arab Emirates : Emirate)\n  Assigned code:\n     a-ts --- United Arab Emirates@"
+"Dutch East Indies\n  USE  Indonesia@"
+"Dutch Guiana\n  USE  Surinam@"
+"Dutch West Indies\n  USE  Netherlands Antilles@"
+"Dza-chu\n  USE  Mekong River@"
+"D¸dekan-sos (Greece)\n  Assigned code:\n     e-gr --- Greece@"
+"Earth --- x@"
+"East (Far East)\n  USE  East Asia@"
+"East (Near East)\n  USE  Middle East@"
+"East (U.S.) --- n-usr@"
+"East Africa Protectorate\n  USE  Kenya@"
+"East Africa, Portuguese\n  USE  Mozambique@"
+"East Africa\n  USE  Africa, East@"
+"East African Horn\n  USE  Africa, Northeast@"
+"East Asia --- ae@"
+"East Berlin\n  USE  Berlin (Germany)@"
+"East China Sea --- an@"
+"East Germany\n  USE  Germany (East)@"
+"East Indies\n  Assigned codes:\n     az --- Asia, South\n     as --- Asia, Southeastern@"
+"East Pakistan (Pakistan)\n  USE  Bangladesh@"
+"East Siberian Region (Russia)\n  USE  Siberia, Eastern (Russia)@"
+"East Timor --- en@"
+"East\n  USE  Orient@"
+"Easter Island --- poea@"
+"Eastern Africa\n  USE  Africa, Eastern@"
+"Eastern Canada\n  USE  Canada, Eastern@"
+"Eastern Europe\n  USE  Europe, Eastern@"
+"Eastern Hemisphere --- xa@"
+"Eastern Mediterranean\n  USE  Middle East@"
+"Eastern Siberia (Russia)\n  USE  Siberia, Eastern (Russia)@"
+"Ecuador --- s-ec@"
+"Egypt --- f-ua@"
+"Eire\n  USE  Ireland@"
+"El Salvador --- nces@"
+"Ellice Islands\n  USE  Tuvalu@"
+"Emerging nations\n  USE  Developing countries@"
+"Enderbury and Canton Islands\n  USE  Canton and Enderbury Islands@"
+"England --- e-uk-en@"
+"English Channel\n  Assigned code:\n     ln --- North Atlantic Ocean@"
+"Equatorial Guinea --- f-eg@"
+"Eritrea --- f-ea\n     Coded f-et (Ethiopia) before Nov. 1993@"
+"Estonia --- e-er@"
+"Ethiopia --- f-et@"
+"Eurasia --- me@"
+"Europe --- e@"
+"Europe and Asia (treated collectively)\n  USE  Eurasia@"
+"Europe, Central --- ec@"
+"Europe, East Central\n     Coded et (Europe, East Central) before Mar. 1988\n  USE  Europe, Central@"
+"Europe, Eastern --- ee@"
+"Europe, Northern --- en@"
+"Europe, Southeastern\n  USE  Balkan Peninsula@"
+"Europe, Southern --- es@"
+"Europe, Western --- ew@"
+"European Economic Community countries\n  Assigned code:\n     e --- Europe@"
+"European Union countries\n  Assigned code:\n     e --- Europe@"
+"Faeroe Islands\n  USE  Faroe Islands@"
+"Falkland Islands --- lsfk@"
+"Far East (Russia)\n  USE  Russian Far East (Russia)@"
+"Far East\n  USE  East Asia@"
+"Far Eastern Region (Russia)\n  USE  Russian Far East (Russia)@"
+"Far West (U.S.)\n  USE  West (U.S.)@"
+"Faroe Islands --- lnfa@"
+"Federal Capital Territory\n  USE  Australian Capital Territory@"
+"Federal German Republic\n  USE  Germany (West)@"
+"Federated States of Micronesia\n  USE  Micronesia (Federated States)@"
+"Federation of Rhodesia and Nyasaland\n  USE  Rhodesia and Nyasaland@"
+"Federation of South Arabia\n  Assigned code:\n     a-ye --- Yemen@"
+"Fernando Po (Equatorial Guinea)\n  Assigned code:\n     f-eg --- Equatorial Guinea@"
+"Fiji --- pofj@"
+"Finland --- e-fi@"
+"Florida --- n-us-fl@"
+"Former Soviet republics\n  USE  Soviet Union@"
+"Former Yugoslav republics\n  USE  Yugoslavia@"
+"Formosa\n  USE  Taiwan@"
+"France --- e-fr@"
+"French Cameroons\n  USE  Cameroon@"
+"French Community --- h@"
+"French Congo\n  USE  Congo (Brazzaville)@"
+"French Equatorial Africa\n  USE  Africa, French-speaking Equatorial@"
+"French Guiana --- s-fg@"
+"French Guinea\n  USE  Guinea@"
+"French India\n  Assigned code:\n     a-ii --- India@"
+"French Indochina\n  USE  Indochina@"
+"French Morocco\n  USE  Morocco@"
+"French Polynesia --- pofp@"
+"French Somaliland\n  USE  Djibouti@"
+"French Southern Indian Ocean Islands\n  USE  Terres australes et antarctiques françaises@"
+"French Southern and Antarctic Lands\n  USE  Terres australes et antarctiques françaises@"
+"French Sudan\n  USE  Mali@"
+"French Territory of the Afars and Issas\n  USE  Djibouti@"
+"French Togoland\n  USE  Togo@"
+"French Union\n  USE  French Community@"
+"French West Africa\n  USE  Africa, French-speaking West@"
+"French West Indies\n  USE  West Indies, French@"
+"French-speaking Equatorial Africa\n  USE  Africa, French-speaking Equatorial@"
+"French-speaking West Africa\n  USE  Africa, French-speaking West@"
+"Friendly Islands\n  USE  Tonga@"
+"Froides, Îles\n  USE  Prince Edward Islands@"
+"Frostbelt (U.S.)\n  USE  Snowbelt States@"
+"Fukien Province (China) --- a-cc-fu@"
+"Fundy, Bay of\n  Assigned code:\n     ln --- North Atlantic Ocean@"
+"Futuna Islands (Wallis and Futuna Islands)\n  Assigned code:\n     powf --- Wallis and Futuna Islands@"
+"Gabon --- f-go@"
+"Galapagos Islands --- pogg@"
+"Gambia --- f-gm@"
+"Gambier Islands\n  Assigned code:\n     pofp --- French Polynesia@"
+"Gaza Strip --- awgz@"
+"Georges Bank\n  Assigned code:\n     ln --- North Atlantic Ocean@"
+"Georgia (Republic) --- a-gs\n     Coded e-ur-gs (Georgia (Republic)) before June 1998@"
+"Georgia (Soviet Union)\n  USE  Georgia (Republic)@"
+"Georgia --- n-us-ga@"
+"Georgian S.S.R. \n  USE  Georgia (Republic)@"
+"German Democratic Republic\n  USE  Germany (East)@"
+"German East Africa\n  USE  Tanzania@"
+"German Federal Republic\n  USE  Germany@"
+"Germany (East) --- e-ge\n     For the eastern part of Germany before 1949 or after 1990 and for the German Democratic Republic between 1949-1990@"
+"Germany (West) --- e-gw\n     For the western part of Germany before 1949 or after 1990 and for the Federal Republic of Germany between 1949-1990@"
+"Germany --- e-gx\n     For Germany as a whole regardless of time period; includes Germany (East) and Germany (West) as a whole between 1949 and 1990@"
+"Germany, Eastern\n  USE  Germany (East)@"
+"Germany, Northern\n  Assigned code:\n     e-gx --- Germany@"
+"Germany, Southern\n  Assigned code:\n     e-gx --- Germany@"
+"Germany, Western\n  USE  Germany (West)@"
+"Ghana (Empire)\n  Assigned code:\n     fw --- Africa, West@"
+"Ghana --- f-gh@"
+"Gibraltar --- e-gi@"
+"Gibraltar, Strait of\n  Assigned codes:\n     e-gi --- Gibraltar\n     mm --- Mediterranean Sea@"
+"Gilbert Islands\n  USE  Kiribati@"
+"Gilbert and Ellice Islands Colony\n     Coded pogn (Gilbert and Ellice Islands) before Mar. 1988\n  Assigned codes:\n     pokb --- Kiribati\n     potv --- Tuvalu@"
+"Gold Coast\n  USE  Ghana@"
+"Great Barrier Reef (Qld.)\n  Assigned code:\n     u-at-qn ---  Queensland@"
+"Great Basin\n  Assigned code:\n     n-usp --- West (U.S.)@"
+"Great Britain --- e-uk@"
+"Great Britain Miscellaneous Island Dependencies --- e-uk-ui@"
+"Great Lakes --- nl@"
+"Great Lakes States\n  USE  Lake States@"
+"Great Plains --- np@"
+"Great Rift Valley --- fr@"
+"Greater Antilles\n     Coded nwga (Greater Antilles) before Mar. 1988\n  USE  West Indies@"
+"Greece --- e-gr@"
+"Greenland --- n-gl@"
+"Grenada --- nwgd@"
+"Grenadines\n     Coded nwgs (Grenadines) before Mar. 1988\n  Assigned code:\n     nwxm --- Saint Vincent and the Grenadines@"
+"Guadalcanal Island (Solomon Islands)\n  Assigned code:\n     pobp --- Solomon Islands@"
+"Guadeloupe --- nwgp@"
+"Guam --- pogu@"
+"Guatemala --- ncgt@"
+"Guernsey\n  Assigned code:\n     e-uk-ui --- Great Britain Miscellaneous Island Dependencies@"
+"Guiana, British\n  USE  Guyana@"
+"Guiana, Dutch\n  USE  Surinam@"
+"Guiana, French\n  USE  French Guiana@"
+"Guinea --- f-gv@"
+"Guinea, Equatorial\n  USE  Equatorial Guinea@"
+"Guinea, French\n  USE  Guinea@"
+"Guinea, Gulf of\n  Assigned code:\n     ls --- South Atlantic Ocean@"
+"Guinea, Portuguese\n  USE  Guinea-Bissau@"
+"Guinea, Spanish\n  USE  Equatorial Guinea@"
+"Guinea-Bissau --- f-pg@"
+"Guinee\n  USE  Guinea@"
+"Gulf States\n  Assigned code:\n     n-usu --- Southern States@"
+"Gulf of Aden\n  USE  Aden, Gulf of@"
+"Gulf of Alaska (Alaska)\n  USE  Alaska, Gulf of (Alaska)@"
+"Gulf of Aqaba\n  USE  Aqaba, Gulf of@"
+"Gulf of Carpentaria (N.T. and Qld.)\n  USE  Carpentaria, Gulf of (N.T. and Qld.)@"
+"Gulf of Guinea\n  USE  Guinea, Gulf of@"
+"Gulf of Mexico\n  USE  Mexico, Gulf of@"
+"Gulf of Oman\n  USE  Oman, Gulf of@"
+"Gulf of Thailand\n  USE  Thailand, Gulf of@"
+"Guyana --- s-gy@"
+"Hainan Island (China)\n  USE  Hainan Province (China)@"
+"Hainan Province (China) --- a-cc-ha\n     Coded a-cc-kn (Kwangtung Province (China)) before June 1998@"
+"Haiti --- nwht@"
+"Hawaii --- n-us-hi@"
+"Heard Island (Heard and McDonald Islands)\n  Assigned code:\n     i-hm --- Heard and McDonald Islands@"
+"Heard and McDonald Islands (Heard and McDonald (slands) --- i-hm@"
+"Hei Ho (China and Russia)\n  USE  Amur River (China and Russia)@"
+"Hei-lung Chiang (China and Russia)\n  USE  Amur River (China and Russia)@"
+"Heilungkiang Province (China) --- a-cc-he@"
+"Himalaya Mountains --- ah@"
+"Hispaniola --- nwhi@"
+"Ho-pei sheng (China)\n  USE  Hopeh Province (China)@"
+"Hoang Ho (China)\n  USE  Yellow River (China)@"
+"Holland\n  USE  Netherlands@"
+"Holy Roman Empire\n  Assigned code:\n     e --- Europe@"
+"Holy See\n  USE  Vatican City@"
+"Homelands (South Africa)\n  Assigned code:\n     f-sa --- South Africa@"
+"Honan Province (China) --- a-cc-ho@"
+"Honduras --- ncho@"
+"Hong Kong (China) a-cc-hk\n     Coded a-hk (Hong Kong) before June 1998@"
+"Hong Kong\n  USE  Hong Kong (China)@"
+"Hoorn Islands\n  USE  Futuna Islands (Wallis and Futuna Islands)@"
+"Hopeh Province (China) --- a-cc-hp@"
+"Hsi Chiang (China)\n  USE  West River (China)@"
+"Hsi-sha Islands\n  USE  Paracel Islands@"
+"Hsin-chiang-wei-wu-erh tzu chih ch'ü (China)\n  USE  Sinkiang Uighur Autonomous Region (China)@"
+"Hu-pei (China)\n  USE  Hupeh Province (China)@"
+"Huang Hai\n  USE  Yellow Sea@"
+"Huang Ho (China)\n  USE  Yellow River (China)@"
+"Hudson Bay --- n-cnh@"
+"Hunan Province (China) --- a-cc-hu@"
+"Hungary --- e-hu@"
+"Hupeh Province (China) --- a-cc-hh@"
+"Huthera (Tanzania)\n  USE  Pemba (Tanzania)@"
+"Hwang Ho (China)\n  USE  Yellow River (China)@"
+"Iberian Peninsula\n     Coded ei (Iberian Peninsula) before Mar. 1988\n  Assigned codes:\n     e-po --- Portugal\n     e-sp --- Spain@"
+"Iceland --- e-ic@"
+"Idaho --- n-us-id@"
+"Ifni\n     Coded f-if (Ifni) before Mar. 1988\n  Assigned code:\n     f-mr --- Morocco@"
+"Illinois --- n-us-il@"
+"India --- a-ii@"
+"India, French\n  USE  French India@"
+"Indian Ocean --- i@"
+"Indian Ocean Islands, French\n  USE  Terres australes et antarctiques françaises@"
+"Indian Ocean Territory, British\n  USE  British Indian Ocean Territory@"
+"Indian Territory\n  Assigned code:\n     n-us-ok --- Oklahoma@"
+"Indiana --- n-us-in@"
+"Indies, East\n  USE  East Indies@"
+"Indies, West\n  USE  West Indies@"
+"Indochina --- ai@"
+"Indonesia --- a-io@"
+"Inner Mongolia (China) --- a-cc-im@"
+"Intercontinental areas (Eastern Hemisphere) --- m@"
+"Intercontinental areas (Western Hemisphere) --- c@"
+"Iowa --- n-us-ia@"
+"Iran --- a-ir@"
+"Iraq --- a-iq@"
+"Ireland (Eire)\n  USE  Ireland@"
+"Ireland --- e-ie@"
+"Ireland, Northern\n  USE  Northern Ireland@"
+"Irian Barat (Indonesia)\n  USE  Irian Jaya (Indonesia)@"
+"Irian Jaya (Indonesia)\n  Assigned code:\n     a-io --- Indonesia@"
+"Irish Republic\n  USE  Ireland@"
+"Irish Sea\n  Assigned code:\n     ln --- North Atlantic Ocean@"
+"Isla de Pascua\n  USE  Easter Island@"
+"Islamic Empire\n  Assigned codes:\n     aw --- Middle East\n     ff --- Africa, North\n     e-sp --- Spain@"
+"Islamic countries\n  Assigned codes:\n     f --- Africa\n     a --- Asia@"
+"Island Dependencies of Great Britain\n  USE  Great Britain Miscellaneous Island Dependencies@"
+"Island Dependencies of the United States in the Caribbean\n  USE  United States Miscellaneous Caribbean Islands@"
+"Island Dependencies of the United States in the Pacific\n  USE  United States Miscellaneous Pacific Islands@"
+"Islands of the Aegean\n  USE  Aegean Islands (Greece and Turkey)@"
+"Islands of the Atlantic\n  Assigned code:\n     l --- Atlantic Ocean@"
+"Islands of the Indian Ocean\n  Assigned code:\n     i --- Indian Ocean@"
+"Islands of the Mediterranean\n  Assigned code:\n     mm --- Mediterranean Sea@"
+"Islands of the Pacific\n  Assigned code:\n     po --- Oceania@"
+"Islands of the South China Sea\n  Assigned code:\n     ao --- South China Sea@"
+"Islas Marquesas de Mendoza (French Polynesia)\n  USE  Marquesas Islands (French Polynesia)@"
+"Isle of Man\n  Assigned code:\n     e-uk-ui --- Great Britain Miscellaneous Island Dependencies@"
+"Isle of Wight (England)\n  Assigned code:\n     e-uk-en --- England@"
+"Israel --- a-is@"
+"Italian East Africa\n  USE  Africa, Northeast@"
+"Italian Somaliland\n  USE  Somalia@"
+"Italy --- e-it@"
+"Ivory Coast\n  USE  Côte d'Ivoire@"
+"Jamaica --- nwjm@"
+"Jammu and Kashmir (India)\n  Assigned code:\n     a-ii --- India@"
+"Jan Mayen Island --- lnjn@"
+"Japan --- a-ja@"
+"Java (Indonesia)\n  Assigned code:\n     a-io --- Indonesia@"
+"Jersey (Channel Islands)\n  Assigned code:\n     e-uk-ui --- Great Britain Miscellaneous Island Dependencies@"
+"Jerusalem\n  Assigned code:\n     a-is --- Israel     and/or\n     awba --- West Bank@"
+"Johnston Island --- poji@"
+"Jordan --- a-jo@"
+"Judaea and Samaria\n  USE  West Bank@"
+"Jupiter --- zju@"
+"Kalimantan Barat (Indonesia)\n  Assigned code:\n     a-io --- Indonesia@"
+"Kampuchea\n  USE  Cambodia@"
+"Kansas --- n-us-ks@"
+"Kansu Province (China) --- a-cc-ka@"
+"Kashmir and Jammu (India)\n  USE  Jammu and Kashmir (India)@"
+"Kashmir\n  USE  Azad Kashmir@"
+"Kazakh S.S.R.\n  USE  Kazakhstan@"
+"Kazakhstan --- a-kz\n     Coded e-ur-kz (Kazakhstan) before June 1998@"
+"Kazakstan\n  USE  Kazakhstan@"
+"Keeling Islands\n  USE  Cocos (Keeling) Islands@"
+"Kentucky --- n-us-ky@"
+"Kenya --- f-ke@"
+"Kerguelen Islands\n  Assigned code:\n     i-fs --- Terres australes et antarctiques françaises@"
+"Kermadec Islands --- poki@"
+"Khmer Republic\n  USE  Cambodia@"
+"Kiangsi Province (China) --- a-cc-ki@"
+"Kiangsu Province (China) --- a-cc-ku@"
+"Kievan Rus\n     Coded e-ur (Soviet Union) before June 1998\n  Assigned code:\n     e-bw --- Belarus\n     e-ru --- Russia (Federation)\n     e-un --- Ukraine@"
+"Kirghiz S.S.R.\n  USE  Kyrgyzstan@"
+"Kiribati --- pokb\n     Coded pogn (Gilbert and Ellice Islands) or poln (Line Islands) before Mar. 1988@"
+"Kirin Province (China) --- a-cc-kr@"
+"Kiritimati (Kiribati)\n  Assigned code:\n     pokb --- Kiribati@"
+"Kongo Kingdom\n  Assigned codes:\n     f-ao --- Angola\n     f-cf --- Congo (Brazzaville)\n     f-cg --- Congo (Democratic Republic)@"
+"Korea (North) --- a-kn@"
+"Korea (Republic)\n  USE  Korea (South)@"
+"Korea (South) --- a-ko@"
+"Korea --- a-kr@"
+"Korean People's Republic\n  USE  Korea (North)@"
+"Kosovo --- e-kv@"
+"Kosrae (Micronesia)\n  Assigned code:\n     pomi --- Micronesia (Federated States)@"
+"Kuang-hsi Chuang tsu tzu chih ch'ü (China)\n  USE  Kwangsi Chuang Autonomous Region (China)@"
+"Kunlun Mountains --- a-cck@"
+"Kuril Islands (Russia)\n     Coded e-ur-ru (Russia Federationion) before June 1998\n  Assigned code:\n     e-ru --- Russia (Federation)@"
+"Kurile Islands (Russia)\n  USE  Kuril Islands (Russia)@"
+"Kuri°skie ostrova (Russia)\n  USE  Kuril Islands (Russia)@"
+"Kusaie (Micronesia)\n  USE  Kosrae (Micronesia)@"
+"Kuwait --- a-ku@"
+"Kwang Sea\n  USE  Yellow Sea@"
+"Kwangsi Chuang Autonomous Region (China) --- a-cc-kc@"
+"Kwangtung Province (China) --- a-cc-kn@"
+"Kweichow Province (China) --- a-cc-kw@"
+"Kwenlun Mountains\n  USE  Kunlun Mountains@"
+"Kyrgyzstan --- a-kg\n     Coded e-ur-kg (Krygystan) before June 1998@"
+"La Plata River (Argentina and Uruguay)\n  USE  Rio de la Plata (Argentina and Uruguay)@"
+"Labrador (Nfld.)\n  Assigned code:\n     n-cn-nf --- Newfoundland and Laborador@"
+"Laccadive, Minicoy, and Amindivi Islands (India)\n  USE  Lakshadweep (India)@"
+"Lake States --- nl@"
+"Lakshadweep (India)\n  Assigned code:\n     a-ii --- India@"
+"Lan-ts'ang Chiang\n  USE  Mekong River@"
+"Lancang Jiang\n  USE  Mekong River@"
+"Laos --- a-ls@"
+"Lapland\n  Assigned codes:\n     e-fi --- Finland\n     e-no --- Norway\n     e-sw --- Sweden@"
+"Latin America --- cl@"
+"Latin Orient\n  Assigned code:\n     aw --- Middle East@"
+"Latvia --- e-lv\n     Coded e-ur-lv (Latvia) before June 1998@"
+"Lebanon --- a-le@"
+"Leeward Islands (West Indies) --- nwli@"
+"Lesotho --- f-lo@"
+"Lesser Antilles\n  USE  Antilles, Lesser@"
+"Lesser Sunda Islands (Indonesia)\n  Assigned code:\n     a-io --- Indonesia@"
+"Levant\n  USE  Middle East@"
+"Liaoning Province (China) --- a-cc-lp@"
+"Liberia --- f-lb@"
+"Libya --- f-ly@"
+"Liechtenstein --- e-lh@"
+"Line Islands --- poln@"
+"Lithuania --- e-li\n     Coded e-ur-li (Lithuania) before June 1998@"
+"Long River (China)\n  USE  Yangtze River (China)@"
+"Loro Sae (Indonesia)\n  USE  Timor Timur (Indonesia)@"
+"Louisiade Archipelago (Papua New Guinea)\n  Assigned code:\n     a-pp --- Papua New Guinea@"
+"Louisiana --- n-us-la@"
+"Low countries\n  USE  Benelux countries@"
+"Loyalty Islands (New Caledonia)\n  Assigned code:\n     ponl --- New Caledonia@"
+"Luxembourg --- e-lu@"
+"Luzon (Philippines)\n  Assigned code:\n     a-ph --- Philippines@"
+"Macao --- a-cc-mh@"
+"Macedonia (Bulgaria)\n  Assigned code:\n     e-bu --- Bulgaria@"
+"Macedonia (Greece)\n  Assigned code:\n     e-gr --- Greece@"
+"Macedonia (Republic) --- e-xn\n     Coded e-yu (Yugoslavia) before Oct. 1992@"
+"Macedonia\n  Assigned codes:\n     e-bu --- Bulgaria\n     e-gr --- \n     e-xn --- Macedonia (Republic)@"
+"Macias Nguema (Equatorial Guinea)\n  USE  Fernando Po (Equatorial Guinea)@"
+"Madagascar --- f-mg@"
+"Madeira Islands --- lnma@"
+"Madura Island (Indonesia)\n  Assigned code:\n     a-io --- Indonesia@"
+"Maine --- n-us-me@"
+"Mainland China\n  USE  China@"
+"Malagasy Republic\n  USE  Madagascar@"
+"Malawi --- f-mw@"
+"Malay Archipelago\n  Assigned code:\n     as --- Asia, Southeastern@"
+"Malay Peninsula\n  Assigned codes:\n     am --- Malaya\n     a-th --- Thailand@"
+"Malaya --- am@"
+"Malaysia --- a-my@"
+"Maldives --- i-xc@"
+"Mali (Empire)\n  Assigned code:\n     fw --- Africa, West@"
+"Mali --- f-ml@"
+"Malta --- e-mm@"
+"Maluku (Indonesia)\n  Assigned code:\n     a-io --- Indonesia@"
+"Malvinas Islands\n  USE  Falkland Islands@"
+"Man, Isle of\n  USE  Isle of Man@"
+"Manchuria (China)\n  Assigned code:\n     a-cc --- China@"
+"Manitoba --- n-cn-mb@"
+"Mariana Islands --- poxd@"
+"Marie-Galante\n  Assigned code:\n     nwgp --- Guadeloupe@"
+"Maritime Provinces --- n-cnm@"
+"Marquesas Islands (French Polynesia)\n  Assigned code:\n     pofp --- French Polynesia@"
+"Mars --- zma@"
+"Marshall Islands --- poxe@"
+"Martinique --- nwmq@"
+"Maryland --- n-us-md@"
+"Massachusetts --- n-us-ma@"
+"Mauritania --- f-mu@"
+"Mauritius --- i-mf@"
+"Mayotte --- i-my\n     Coded i-cq (Comoros) before Mar. 1988@"
+"McDonald Island\n  Assigned code:\n     i-hm --- Heard and McDonald Islands@"
+"Mediterranean Region --- mm@"
+"Mediterranean Region, Eastern\n  USE  Middle East@"
+"Mediterranean Sea --- mm@"
+"Mekong River --- ag@"
+"Melanesia --- pome@"
+"Melilla (Spain)\n  Assigned code:\n     f-sh --- Spanish North Africa@"
+"Mendaña\n  USE  Marquesas Islands (French Polynesia)@"
+"Mercury --- zme@"
+"Mexico --- n-mx@"
+"Mexico, Gulf of --- nm@"
+"Michigan --- n-us-mi@"
+"Micronesia (Federated States) --- pomi\n     Coded pott (Micronesia) before Mar. 1988@"
+"Micronesia --- pott@"
+"Middle America\n     Coded cm (Middle America) before Mar. 1988\n  USE  Central America@"
+"Middle Atlantic States --- n-usl@"
+"Middle Congo\n  USE  Congo (Brazzaville)@"
+"Middle East --- aw@"
+"Middle States\n  USE  Middle Atlantic States@"
+"Middle West --- n-usc@"
+"Mideast\n  USE  Middle East@"
+"Midway Islands --- poxf@"
+"Midwest\n  USE  Middle West@"
+"Mindanao Island (Philippines)\n  Assigned code:\n     a-ph --- Philippines@"
+"Minnesota --- n-us-mn@"
+"Miquelon\n  Assigned code:\n     n-xl --- Saint Pierre and Miquelon@"
+"Mississippi --- n-us-ms@"
+"Mississippi River --- n-usm@"
+"Missouri --- n-us-mo@"
+"Missouri River --- n-uss@"
+"Moldavia\n  Assigned code:\n     e-rm --- Romania@"
+"Moldavian S.S.R.\n  USE  Moldova@"
+"Moldova --- e-mv\n     Coded e-ur-mv (Moldova) before June 1998@"
+"Moluccas\n  USE  Maluku (Indonesia)@"
+"Monaco --- e-mc@"
+"Mongolia (Inner Mongolia)\n  USE  Inner Mongolia (China)@"
+"Mongolia --- a-mp@"
+"Mongolian People's Republic\n  USE  Mongolia@"
+"Montana --- n-us-mt@"
+"Montenegro --- e-mo@"
+"Montserrat --- nwmj@"
+"Moon --- zmo@"
+"Morocco --- f-mr@"
+"Mozambique --- f-mz@"
+"Muscat and Oman\n  USE  Oman@"
+"Namibia --- f-sx@"
+"Nansha Islands\n  USE  Spratly Islands@"
+"Nauru --- ponu@"
+"Near East\n  USE  Middle East@"
+"Nebraska --- n-us-nb@"
+"Negros Island (Philippines)\n  Assigned code:\n     a-ph --- Philippines@"
+"Nepal --- a-np@"
+"Neptune --- zne@"
+"Netherlands --- e-ne@"
+"Netherlands Antilles --- nwna@"
+"Netherlands East Indies\n  USE  Indonesia@"
+"Netherlands West Indies\n  USE  Netherlands Antilles@"
+"Nevada --- n-us-nv@"
+"Nevis\n  Assigned code:\n     nwxi --- Saint Kitts and Nevis@"
+"New Britain Island (Papua New Guinea)\n  Assigned code:\n     a-pp --- Papua New Guinea@"
+"New Brunswick --- n-cn-nk@"
+"New Caledonia --- ponl@"
+"New England --- n-usn@"
+"New France\n  Assigned code:\n     n --- North America@"
+"New Guinea (Territory)\n  Assigned code:\n     a-pp --- Papua New Guinea@"
+"New Guinea --- a-nw@"
+"New Guinea Island\n  USE  New Guinea@"
+"New Hampshire --- n-us-nh@"
+"New Hebrides\n  USE  Vanuatu@"
+"New Ireland Island (Papua New Guinea)\n  Assigned code:\n     a-pp --- Papua New Guinea@"
+"New Jersey --- n-us-nj@"
+"New Mexico --- n-us-nm@"
+"New South Wales --- xna@"
+"New York (State) --- n-us-ny@"
+"New Zealand --- u-nz@"
+"Newfoundland --- n-cn-nf@"
+"Nicaragua --- ncnq@"
+"Niger --- f-ng@"
+"Niger River --- fi@"
+"Nigeria --- f-nr@"
+"Nile River --- fl@"
+"Ninghsia Province (China)\n  USE  Ningsia Hui Autonomous Region  (China)@"
+"Ningsia Hui Autonomous Region (China) a-cc-nn@"
+"Niue --- poxh@"
+"Non-Black Earth Region (Russia)\n  USE  Non-Chernozem Region (Russia)@"
+"Non-Chernozem Region (Russia)\n     Coded e-ur-ru (Russia Federation) before June 1998\n  Assigned code:\n     e-ru --- Russia (Federation)@"
+"Norfolk Island\n  Assigned code:\n     u-at --- Australia@"
+"North Africa\n  USE  Africa, North@"
+"North America --- n@"
+"North Atlantic Ocean --- ln@"
+"North Borneo\n  USE  Sabah@"
+"North Carolina --- n-us-nc@"
+"North Caucasus (Russia)\n  USE  Caucasus, Northern (Russia)@"
+"North Central States\n  USE  Middle West@"
+"North Dakota --- n-us-nd@"
+"North Korea\n  USE  Korea (North)@"
+"North Pacific Ocean --- pn@"
+"North Sea\n  Assigned code:\n     ln --- North Atlantic Ocean@"
+"North Vietnam\n  USE  Vietnam@"
+"Northeast (U.S.)\n  USE  Northeastern States@"
+"Northeast Africa\n  USE  Africa, Northeast@"
+"Northeast Passage\n  Assigned code:\n     r --- Arctic regions@"
+"Northeastern States --- n-use@"
+"Northern Canada\n  USE  Canada, Northern@"
+"Northern Caucasus (Russia)\n  USE  Caucasus, Northern (Russia)@"
+"Northern Europe\n  USE  Europe, Northern@"
+"Northern Hemisphere --- xb@"
+"Northern Ireland --- e-uk-ni@"
+"Northern Mariana Islands\n  USE  Mariana Islands@"
+"Northern Rhodesia\n  USE  Zambia@"
+"Northern Russia\n  USE  Russia, Northerm@"
+"Northern Soviet Union\n  USE  Russia, Northern@"
+"Northern Territory --- u-at-no@"
+"Northwest (U.S.)\n     Coded n-usw (Northwest (U.S.)) before Mar. 1988\n  USE  Northwest, Pacific@"
+"Northwest Africa\n  USE  Africa, Northwest@"
+"Northwest Passage\n  Assigned code:\n     r --- Arctic regions@"
+"Northwest Territories --- n-cn-nt@"
+"Northwest, Canadian\n  Assigned code:\n     n-cn --- Canada@"
+"Northwest, Old\n  Assigned code:\n     n-usc --- Middle West@"
+"Northwest, Pacific\n  Assigned codes:\n     n-usp --- West (U.S.)  and if appropriate\n     n-cn-bc  --- British Columbia@"
+"Northwestern Soviet Union\n  USE  Soviet Union, Northwestern@"
+"Northwestern States\n  Assigned codes:\n     n-usc --- Middle West\n     n-usp --- West (U.S.)@"
+"Norway --- e-no@"
+"Norwegian Sea\n  Assigned code:\n     ln --- North Atlantic Ocean@"
+"Nova Scotia --- n-cn-ns@"
+"Nunavut --- n-cn-nu@"
+"Nyasaland\n  USE  Malawi@"
+"Ocean Island (Kiribati)\n  USE  Banaba@"
+"Oceania --- po@"
+"Oceania, French\n  USE  French Polynesia@"
+"Oceanica\n  USE  Oceania@"
+"Ohio --- n-us-oh@"
+"Ohio River --- n-uso@"
+"Okinawa Island (Japan)\n     Coded a-ok (Okinawa) before 1984\n  Assigned code:\n     a-ja --- Japan@"
+"Oklahoma --- n-us-ok@"
+"Oman --- a-mk@"
+"Oman, Gulf of\n  Assigned code:\n     au --- Arabian Sea@"
+"Ontario --- n-cn-on@"
+"Oregon --- n-us-or@"
+"Orient\n  Assigned code:\n     a --- Asia@"
+"Orkney (Scotland)\n  Assigned code:\n     e-uk-st --- Scotland@"
+"Outer Mongolia\n  USE  Mongolia@"
+"Outer space --- zo@"
+"Ozark Mountains\n  Assigned codes:\n     n-us-ar --- Arkansas\n     n-us-mo --- Missouri\n     n-us-ok --- Oklahoma@"
+"Pacific Area\n  Assigned code:\n     p --- Pacific Ocean@"
+"Pacific Coast (North America)\n  Assigned code:\n     n --- North America@"
+"Pacific Island Dependencies of the United States\n  USE  United States Miscellaneous Pacific Islands@"
+"Pacific Islands (Ter.)\n  USE  Pacific Islands (Trust Territory)@"
+"Pacific Islands (Trust Territory)\n  Assigned code:\n     poup --- United States Miscellaneous Pacific Islands@"
+"Pacific Northwest\n  USE  Northwest, Pacific@"
+"Pacific Ocean --- p@"
+"Pacific Ocean, North\n  USE  North Pacific Ocean@"
+"Pacific Ocean, South\n  USE  South Pacific Ocean@"
+"Pacific States\n  Assigned codes:\n     n-us-ca --- California\n     n-us-or --- Oregon\n     n-us-wa --- Washington (State)@"
+"Pacific and Mountain States\n  USE  West (U.S.)@"
+"Pakistan --- a-pk@"
+"Palau --- popl\n     Coded poci (Caroline Islands) before Mar. 1988@"
+"Palestine\n  Assigned code:\n     a-is --- Israel@"
+"Panama --- ncpn@"
+"Panama Canal Zone\n  USE  Canal Zone@"
+"Panay Island (Philippines)\n  Assigned code:\n     a-ph --- Philippines@"
+"Pannonia\n  Assigned codes:\n     e-au --- Austria\n     e-hu --- Hungary\n     e-yu --- Yugoslavia@"
+"Papua New Guinea --- a-pp@"
+"Papua\n  Assigned code:\n     a-pp --- Papua New Guinea@"
+"Paracel Islands --- aopf@"
+"Paraguay --- s-py@"
+"Pascua Island\n  USE  Easter Island@"
+"Peiping (China)\n  USE  Peking (China)@"
+"Peking (China) --- a-cc-pe@"
+"Pelew\n  USE  Palau@"
+"Pemba (Zanzibar)\n  Assigned code:\n     f-tz --- Tanzania@"
+"Pennsylvania --- n-us-pa@"
+"People's Democratic Republic of Algeria\n  USE  Algeria@"
+"People's Democratic Republic of Yemen\n  USE  Yemen@"
+"People's Republic of Angola\n  USE  Angola@"
+"People's Republic of Benin\n  USE  Benin@"
+"People's Republic of Bulgaria\n  USE  Bulgaria@"
+"People's Republic of China\n  USE  China@"
+"People's Republic of Croatia\n  USE  Croatia@"
+"People's Republic of Mozambique\n  USE  Mozambique@"
+"People's Socialist Republic of Albania\n  USE  Albania@"
+"Persia\n  USE  Iran@"
+"Persian Gulf --- ap@"
+"Persian Gulf States\n  Assigned code:\n     ar --- Arabian Peninsula@"
+"Peru --- s-pe@"
+"Pescadores Islands\n  Assigned code:\n     a-ch --- Taiwan@"
+"Philippine Islands\n  USE  Philippines@"
+"Philippine Sea\n  Assigned code:\n     pn --- North Pacific Ocean@"
+"Philippines --- a-ph@"
+"Phoenix Islands (Kiribati)\n  Assigned code:\n     pokb --- Kiribati@"
+"Pirineos\n  USE  Pyrenees@"
+"Pitcairn Island --- popc@"
+"Plata, Rio de la (Argentina and Uruguay)\n  USE  Rio del la Plata (Argentina and Uruguay)@"
+"Plate River (Argentina and Uruguay)\n  USE  Rio de la Plata (Argentina and Uruguay)@"
+"Pleasant Island\n  USE  Nauru@"
+"Pluto --- zpl@"
+"Po Gulf (China)\n  USE  Po Hai (China)@"
+"Po Hai (China) --- a-ccp@"
+"Pohnpei (Micronesia)\n  Assigned codes:\n     pomi --- Micronesia (Federated States)@"
+"Poland --- e-pl@"
+"Polar regions\n  Assigned codes:\n     t --- Antarctica\n     r --- Arctic regions@"
+"Polynesia --- pops@"
+"Polynesia, French\n  USE  French Polynesia@"
+"Ponape (Micronesia)\n  USE  Pohnpei (Micronesia)@"
+"Portugal --- e-po@"
+"Portuguese East Africa\n  USE  Mozambique@"
+"Portuguese Guinea\n  USE  Guinea-Bissau@"
+"Portuguese Timor\n  USE  Timor Timur (Indonesia)@"
+"Portuguese West Africa\n  USE  Angola@"
+"Prairie Provinces --- n-cnp@"
+"Pratas Islands\n  Assigned code:\n     a-cc-kn --- Kwangtung Province (China)@"
+"Prince Edward Island --- n-cn-pi@"
+"Prince Edward Islands\n  Assigned code:\n     f-sa --- South Africa@"
+"Prussia (Germany)\n  Assigned code:\n     e-gx --- Germany@"
+"Puerto Rico --- nwpr@"
+"Pyrenees --- ep@"
+"Qatar --- a-qa@"
+"Queensland --- u-at-qn@"
+"Quebec (Province) --- n-cn-qu@"
+"R.S.F.S.R.\n  USE  Russia (Federation)@"
+"Red Sea --- mr@"
+"Reka Amur (China and Russia)\n  USE  Amur River (China and Russia)@"
+"Republic of Cape Verde\n  USE  Cape Verde@"
+"Republic of Ireland\n  USE  Ireland@"
+"Republic of Palau\n  USE  Palau@"
+"Republic of Vanuatu\n  USE  Vanuatu@"
+"Republique de Guinee\n  USE  Guinea@"
+"Reunion\n  [i-re]@"
+"Rhine River --- er@"
+"Rhode Island --- n-us-ri@"
+"Rhodesia and Nyasaland\n  Assigned codes:\n     f-mw --- Malawi\n     f-za --- Zambia\n     f-rh --- Zimbabwe@"
+"Rhodesia, Southern\n  USE  Zimbabwe@"
+"Rhodesia\n  Assigned codes:\n     f-za --- Zambia\n     f-rh --- Zimbabwe@"
+"Rift Valley\n  USE  Great Rift Valley@"
+"Rio Zambezi\n  USE  Zambezi River@"
+"Rio de la Plata (Argentina and Uruguay) --- sp@"
+"Rocky Mountains --- nr@"
+"Roman Empire\n  USE  Rome@"
+"Romania --- e-rm@"
+"Rome\n  Assigned codes:\n     ff --- Africa, North\n     e --- Europe\n     aw --- Middle East@"
+"Ruanda-Urundi\n  Assigned codes:\n     f-bd --- Burundi\n     f-rw --- Rwanda@"
+"Rumania\n  USE  Romania@"
+"Russia (Federation) --- e-ru\n     Coded e-ur-ru (Russia (Federation)) before June 1998@"
+"Russia, Northern\n     Coded e-ur-ru (Russia (Federation)) before June 1998\n  Assigned code:\n     e-ru --- Russia (Federation)@"
+"Russia\n  Assigned code:\n     e-ur --- Soviet Union@"
+"Russian Empire\n  USE  Russia@"
+"Russian Far East (Russia) --- e-urf@"
+"Russian Republic\n  USE  Russia (Federation)@"
+"Russian S.F.S.R. \n  USE  Russia (Federation)@"
+"Russian Soviet Federated Socialist Republic\n  USE  Russia (Federation)@"
+"Rwanda --- f-rw@"
+"Rwanda-Urundi\n  USE  Ruanda-Urundi@"
+"Ryukyu Islands, Southern\n     Coded pory (Ryukyu Islands, Southern) before 1984\n  Assigned code:\n     a-ja --- Japan@"
+"Ryukyu Islands\n  Assigned code:\n     a-ja --- Japan@"
+"Reunion --- i-re@"
+"Río Muni\n  USE  Equatorial Guinea@"
+"Saba (Netherlands Antilles) --- nwsd@"
+"Sabah\n  Assigned code:\n     a-my --- Malaysia@"
+"Sahara --- fd@"
+"Sahara Desert\n  USE  Sahara@"
+"Sahel\n  Assigned code:\n     f --- Africa@"
+"Saint Bartholomew\n  USE  Saint-Barthelemy@"
+"Saint Barts\n  USE  Saint-Barthelemy@"
+"Saint Christopher-Nevis\n  USE  Saint Kitts and Nevis@"
+"Saint Eustatius (Netherlands Antilles) --- nweu@"
+"Saint Helena --- lsxj@"
+"Saint Kitts and Nevis --- nwxi@"
+"Saint Kitts-Nevis-Anguilla\n  Assigned codes:\n     nwxa --- Anguilla\n     nwxi --- Saint Kitts and Nevis@"
+"Saint Kitts\n  Assigned code:\n     nwxi --- Saint Kitts and Nevis@"
+"Saint Lawrence River\n  Assigned codes:\n     n-cn --- Canada\n     n-us --- United States@"
+"Saint Lucia --- nwxk@"
+"Saint Martin --- nwst@"
+"Saint Pierre and Miquelon --- n-xl@"
+"Saint Vincent and the Grenadines --- nwxm@"
+"Saint Vincent\n  Assigned code:\n     nwxm --- Saint Vincent and the Grenadines@"
+"Saint-Barthelemy\n     Coded nwsb (Saint-Barthelemy) before  Mar. 1988\n  Assigned code:\n     nwgp --- Guadeloupe@"
+"Sakha (Russia)\n  Assigned code:\n     e-ru --- Russia (Federation)@"
+"Sakhalin Ula (China and Russia)\n  USE  Amur River (China and Russia)@"
+"Salvador\n  USE  El Salvador@"
+"Salvage Islands (Madeira Islands)\n  USE  Selvagens Islands (Madeira Islands)@"
+"Salvages (Madeira Islands)\n  USE  Selvagens Islands (Madeira Islands)@"
+"Samar (Philippines)\n  Assigned code:\n     a-ph --- Philippines@"
+"Samoa  --- pows@"
+"Samoa (Islands)\n  USE  Samoan Islands@"
+"Samoa, American\n  USE  American Samoa@"
+"Samoan Islands --- posh@"
+"San Marino --- e-sm@"
+"Sandwich Islands, South\n  USE  South Georgia and South Sandwich Islands@"
+"Santa Cruz Islands (Solomon Islands)\n     Coded posc (Santa Cruz Islands) before Mar. 1988\n  Assigned code:\n     pobp --- Solomon Islands@"
+"Sao Tome and Principe --- f-sf@"
+"Sarawak\n  Assigned code:\n     a-my --- Malaysia@"
+"Sardinia (Italy)\n  Assigned code:\n     e-it --- Italy@"
+"Saskatchewan --- n-cn-sn@"
+"Saturn --- zsa@"
+"Saudi Arabia --- a-su@"
+"Scandinavia --- ev@"
+"Scotland --- e-uk-st@"
+"Selvagens Islands (Madeira Islands)\n  Assigned code:\n     lnma --- Madeira Islands@"
+"Senegal --- f-sg@"
+"Serbia --- e-rb@"
+"Serbia and Montenegro --- e-yu@"
+"Seychelles --- i-se@"
+"Shan States\n  Assigned code:\n     a-br --- Burma@"
+"Shanghai (China) --- a-cc-sm@"
+"Shansi Province (China) --- a-cc-sh@"
+"Shantung Province (China) --- a-cc-sp@"
+"Shensi Province (China) --- a-cc-ss@"
+"Shetland (Scotland)\n  Assigned code:\n     e-uk-st --- Scotland@"
+"Shinnan Islands\n  USE  Spratly Islands@"
+"Si River (China)\n  USE  West River (China)@"
+"Si-kiang (China)\n  USE  West River (China)@"
+"Siam, Gulf of\n  USE  Thailand, Gulf of@"
+"Siam\n  USE  Thailand@"
+"Siberia (Russia) --- e-urs@"
+"Siberia, Eastern (Russia) --- e-ure@"
+"Siberia, Northeastern (Russia)\n  Assigned code:\n     e-urs --- Siberia (Russia)@"
+"Siberia, Western (Russia) --- e-urw@"
+"Sicily (Italy)\n  Assigned code:\n     e-it --- Italy@"
+"Sierra Leone --- f-sl@"
+"Sikkim (India)\n     Coded a-sk (Sikkim) before Mar. 1988\n  Assigned code:\n     a-ii --- India@"
+"Singapore --- a-si@"
+"Sinkiang Uighur Autonomous Region (China) --- a-cc-su@"
+"Sint Eustatius (Netherlands Antilles)\n  USE  Saint Eustatius (Netherlands Antilles)@"
+"Sint Maarten\n  USE  Saint Martin@"
+"Skagerrak (Denmark and Norway)\n  Assigned code:\n     ln --- North Atlantic Ocean@"
+"Slovak Socialist Republic (Czechoslovakia)\n  USE  Slovakia@"
+"Slovakia --- e-xo\n     Coded e-cs (Czechoslovakia) before May 1993@"
+"Slovenia --- e-xv\n     Coded e-yu (Yugoslavia) before Oct. 1992@"
+"Snowbelt States\n  Assigned code:\n     n-us --- United States@"
+"Society Islands (French Polynesia)\n  Assigned code:\n     pofp --- French Polynesia@"
+"Socotra (Yemen)\n     Coded i-xo (Socotra Island) before Mar. 1988; Coded a-ys (Yemen (People's Democratic Republic) before Oct. 1992\n  Assigned code:\n     a-ye --- Yemen@"
+"Sokotra (Yemen)\n  USE  Socotra (Yemen)@"
+"Solomon Islands --- pobp\n     Coded also posn (Solomon Islands) before Mar. 1988@"
+"Solar system --- zs@"
+"Somali Republic\n  USE  Somalia@"
+"Somalia --- f-so@"
+"Somaliland, French\n  USE  Djibouti@"
+"Song Tíên Giang\n  USE  Mekong River@"
+"Songhai Empire\n  Assigned codes:\n     f-ml --- Mali\n     f-ng --- Niger\n     f-nr --- Nigeria@"
+"South Africa --- f-sa@"
+"South America --- s@"
+"South Arabia, Federation of\n  USE  Federation of South Arabia@"
+"South Asia\n  USE  Asia, South@"
+"South Atlantic Ocean --- ls@"
+"South Atlantic States\n  Assigned code:\n     n-usu --- Southern States@"
+"South Australia --- u-at-sa@"
+"South Carolina --- n-us-sc@"
+"South China Sea --- ao@"
+"South Dakota --- n-us-sd@"
+"South Georgia and South Sandwich Islands --- lsxs\n     Coded lsfk (Falkland Islands) before Oct. 1992@"
+"South Korea\n  USE  Korea (South)@"
+"South Orkney Islands\n  Assigned code:\n     lsfk --- Falkland Islands@"
+"South Pacific Ocean --- ps@"
+"South Sandwich Islands\n     Coded lsfk (Falkland Islands) before Oct. 1992\n  USE  South Georgia and South Sandwich Islands@"
+"South Shetland Islands (Antarctica)\n     Coded lsfk (Falkland Islands) before Mar. 1998\n  Assigned code:\n     t --- Antarctica@"
+"South Vietnam\n     Coded a-vs (Viet Nam, South) before Mar. 1988\n  USE  Vietnam (Republic)@"
+"South-West Africa\n  USE  Namibia@"
+"Southeast Asia\n  USE  Asia, Southeastern@"
+"Southeastern Asia\n  USE  Asia, Southeastern@"
+"Southeastern Europe\n  USE  Balkan Peninsula@"
+"Southern Africa\n  USE  Africa, Southern@"
+"Southern Cameroons\n  USE  Cameroon@"
+"Southern Europe\n  USE  Europe, Southern@"
+"Southern Hemisphere --- xc@"
+"Southern Rhodesia\n  USE  Zimbabwe@"
+"Southern Soviet Union\n  USE  Soviet Union, Southern@"
+"Southern States --- n-usu@"
+"Southern Yemen\n  USE  Yemen@"
+"Southwest, New --- n-ust@"
+"Southwest, Old\n  Assigned code:\n     n-usu --- Southern States@"
+"Southwestern States\n  Assigned codes:\n     n-usu --- Southern States\n     n-ust --- Southwest, New@"
+"Soviet Central Asia\n  USE  Asia, Central@"
+"Soviet Far East (Russia)\n     Coded e-uro (Soviet Central Asia) before 1994\n  USE  Russian Far East (Russia)@"
+"Soviet Union --- e-ur@"
+"Soviet Union, Northern\n  USE  Russia, Northern@"
+"Soviet Union, Northwestern --- e-urn@"
+"Soviet Union, Southern\n  Assigned code:\n     e-ur --- Soviet Union@"
+"Soviet Union, Western\n  Assigned code:\n     e-ur --- Soviet Union@"
+"Spain --- e-sp@"
+"Spanish Guinea\n  USE  Equatorial Guinea@"
+"Spanish Main\n  Assigned code:\n     cc --- Caribbean Area@"
+"Spanish North Africa --- f-sh@"
+"Spanish Sahara\n  USE  Western Sahara@"
+"Spanish Territories in Northern Morocco\n  USE  Spanish North Africa@"
+"Spitsbergen Island (Norway)\n  Assigned code:\n     lnsb --- Svalbard (Norway)@"
+"Spratly Islands --- aoxp@"
+"Sri Lanka --- a-ce@"
+"St. Barthelemy\n  USE  Saint-Barthelemy@"
+"St. Christopher-Nevis-Anguilla\n  USE  Saint Kitts-Nevis-Anguilla@"
+"St. Eustatius (Netherlands Antilles)\n  USE  Saint Eustatius (Netherlands Antilles)@"
+"St. Helena\n  USE  Saint Helena@"
+"St. Lucia\n  USE  Saint Lucia@"
+"St. Martin\n  USE  Saint Martin@"
+"St. Pierre and Miquelon\n  USE  Saint Pierre and Miquelon@"
+"St. Vincent\n  USE  Saint Vincent@"
+"Statia (Netherlands Antilles)\n  USE  Saint Eustatius (Netherlands Antilles)@"
+"Strait of Gibraltar\n  USE  Gibraltar, Strait of@"
+"Straits Settlements\n  Assigned codes:\n     a-my --- Malaysia\n     a-si --- Singapore@"
+"Sub-Saharan Africa\n  USE  Africa, Sub-Saharan@"
+"Sudan (Region) --- fn@"
+"Sudan --- f-sj@"
+"Sudan, French\n  USE  Mali@"
+"Suez Canal (Egypt) --- fu@"
+"Sulawesi (Indonesia)\n  USE  Celebes (Indonesia)@"
+"Sumatra (Indonesia)\n  Assigned code:\n     a-io --- Indonesia@"
+"Sun --- zsu@"
+"Sunbelt States\n  Assigned codes:\n     n-usu --- Southern States\n     n-ust --- Southwest, New\n  and if appropriate\n     n-us-hi  Hawaii@"
+"Sunda Islands, Lesser (Indonesia)\n  USE  Lesser Sunda Islands (Indonesia)@"
+"Surinam --- s-sr@"
+"Suriname\n  USE  Surinam@"
+"Svalbard (Norway) --- lnsb@"
+"Swan Islands (Honduras) --- nwsv@"
+"Swaziland --- f-sq@"
+"Sweden --- e-sw@"
+"Switzerland --- e-sz@"
+"Syria --- a-sy@"
+"Szechwan Province (China) --- a-cc-sz@"
+"São Thome e Príncipe\n  USE  Sao Tome and Principe@"
+"T.A.A.F.\n  USE  Terres australes et antarctiques françaises@"
+"Tadzhik Soviet Socialist Republic\n  USE  Tajikistan@"
+"Taiwan --- a-ch@"
+"Tajik S.S.R.\n  USE  Tajikistan@"
+"Tajikistan --- a-ta\n     Coded e-ur-ta (Tajikistan) before June 1998@"
+"Tanganyika\n  Assigned code:\n     f-tz --- Tanzania@"
+"Tangier (Morocco)\n  Assigned code:\n     f-mr --- Morocco@"
+"Tanzania --- f-tz@"
+"Tasmania --- u-at-tm@"
+"Tennessee --- n-us-tn@"
+"Terres australes et antarctiques françaises --- i-fs@"
+"Texas --- n-us-tx@"
+"Thailand --- a-th@"
+"Thailand, Gulf of --- af@"
+"Thian Shan\n  USE  Tien Shan@"
+"Third World\n  USE  Developing countries@"
+"Tian Shan\n  USE  Tien Shan@"
+"Tibesti Mountains\n  Assigned codes:\n     f-cd --- Chad\n     f-ly --- Libya\n     f-ng --- Niger@"
+"Tibet (China) --- a-cc-ti@"
+"Tibetan Autonomous Region (China)\n  USE  Tibet (China)@"
+"Tien Mountains\n  USE  Tien Shan@"
+"Tien Shan --- at@"
+"Tientsin (China) --- a-cc-tn@"
+"Timor Island (Indonesia)\n  Assigned code:\n     a-io --- Indonesia@"
+"Timor Sea\n  Assigned code:\n     i --- Indian Ocean@"
+"Timor Timur (Indonesia)\n     Coded a-pt (Portuguese Timor) before Apr. 21, 1980\n  Assigned code:\n     a-io --- Indonesia@"
+"Timor, Portuguese\n  USE  Timor Timur (Indonesia)@"
+"Tobago\n  Assigned code:\n     nwtr --- Trinidad and Tobago@"
+"Togo --- f-tg@"
+"Togoland (British)\n  Assigned code:\n     f-gh --- Ghana@"
+"Togoland (French)\n  USE  Togo@"
+"Togoland\n  Assigned codes:\n     f-gh --- Ghana\n     f-tg --- Togo@"
+"Tokelau --- potl@"
+"Tonga --- poto@"
+"Tonga Islands\n  USE  Tonga@"
+"Torres Strait Islands (Qld.)\n  Assigned code:\n     u-at-qn --- Queensland@"
+"Transcaucasia\n     Coded e-ur-ai (Armenia (Republic)), e-ur-aj (Azerbaijan), e-ur-gs (Georgia (Republic)) before June 1998\n  Assigned codes:\n     e-ur-ai --- Armenia (Republic)\n     e-ur-aj --- Azerbaijan\n     e-ur-gs --- Georgia (Republic)@"
+"Transjordan\n  USE  Jordan@"
+"Trinidad and Tobago --- nwtr@"
+"Trinidad\n  Assigned code:\n     nwtr --- Trinidad and Tobago@"
+"Tristan da Cunha --- lstd@"
+"Trobriand Islands (Papua New Guinea)\n  Assigned code:\n     a-pp --- Papua New Guinea@"
+"Tropics --- w@"
+"Trucial States\n  USE  United Arab Emirates@"
+"Truk (Micronesia)\n  Assigned code:\n     pomi --- Micronesia (Federated States)@"
+"Trust Territory of the Pacific Islands\n  USE  Pacific Islands (Trust Territory)@"
+"Tsinghai Province (China) --- a-cc-ts@"
+"Tuamotu Archipelago (French Polynesia)\n  Assigned code:\n     pofp --- French Polynesia@"
+"Tubuai Islands (French Polynesia)\n  USE  Austral Islands (French Polynesia)@"
+"Tunisia --- f-ti@"
+"Turkey --- a-tu@"
+"Turkmen S.S.R.\n  USE  Turkmenistan@"
+"Turkmenistan --- a-tk\n     Coded e-ur-tk (Turkmenistan) before June 1998@"
+"Turks and Caicos Islands --- nwtc@"
+"Tuvalu --- potv\n     Coded pogn (Gilbert and Ellice Islands) before Mar. 1988@"
+"U.S.S.R.\n  USE  Soviet Union@"
+"Ubangi Shari\n  USE  Central African Republic@"
+"Uganda --- f-ug@"
+"Ukraine --- e-un\n     Coded e-ur-un (Ukraine) before June 1998@"
+"Underdeveloped areas\n  USE  Developing countries@"
+"Union Islands\n  USE  Tokelau@"
+"Union of South Africa\n  USE  South Africa@"
+"United Arab Emirates --- a-ts@"
+"United Arab Republic\n  Assigned codes:\n     f-ua --- Egypt\n     a-sy --- Syria@"
+"United Kingdom Miscellaneous Island Dependencies\n  USE  Great Britain Miscellaneous Island Dependencies@"
+"United Kingdom\n  USE  Great Britain@"
+"United States --- n-us@"
+"United States Miscellaneous Caribbean Islands --- nwuc@"
+"United States Miscellaneous Pacific Islands --- poup@"
+"Upper Volta\n  USE  Burkina Faso@"
+"Ural Mountains (Russia) --- e-uru@"
+"Uranus --- zur@"
+"Uruguay --- s-uy@"
+"Utah --- n-us-ut@"
+"Uvea Island (Wallis and Futuna Islands)\n  Assigned code:\n     powf --- Wallis and Futuna Islands@"
+"Uzbek S.S.R. \n  USE  Uzbekistan@"
+"Uzbekistan --- a-uz\n     Coded e-ur-uz (Uzbekistan) before June 1998@"
+"Vanuatu --- ponn@"
+"Vatican City --- e-vc@"
+"Venezuela --- s-ve@"
+"Venus --- zve@"
+"Vermont --- n-us-vt@"
+"Victoria --- u-at-vi@"
+"Vietnam (Republic)\n     Coded a-vn (Viet Nam, South) before Mar. 1988\n  Assigned code:\n     a-vt --- Vietnam@"
+"Vietnam --- a-vt\n     Coded a-vn (Viet Nam, North) before Mar. 1988@"
+"Vietnam, North\n  USE  Vietnam@"
+"Vietnam, South\n  USE  Vietnam (Republic)@"
+"Virgin Islands (American)\n  USE  Virgin Islands of the United States@"
+"Virgin Islands (Danish)\n  USE  Virgin Islands of the United States@"
+"Virgin Islands (Great Britain)\n  USE  British Virgin Islands@"
+"Virgin Islands (Presidency)\n  USE  British Virgin Islands@"
+"Virgin Islands of the United States --- nwvi@"
+"Virgin Islands, British\n  USE  British Virgin Islands@"
+"Virgin Islands\n     Coded nwvr (Virgin Islands) before Mar. 1988\n  USE  British Virgin Islands@"
+"Virginia --- n-us-va@"
+"Volga River (Russia) --- e-urp@"
+"Volgo-Viatskii Region (Russia)\n     Coded e-urv (Volgo-Viatskii Region, RSFSR) before Mar. 1988\n  Assigned code:\n     e-ru --- Russia (Federation)@"
+"Volta River (Ghana) --- fv@"
+"Wake Island --- powk@"
+"Wales --- e-uk-wl@"
+"Wallis and Futuna Islands --- powf@"
+"Washington (D.C.) --- n-us-dc@"
+"Washington (State) --- n-us-wa@"
+"Washington Region\n  Assigned codes:\n     n-us-md --- Maryland\n     n-us-va --- Virginia\n     n-us-dc --- Washington (D.C.)@"
+"West (Canada)\n  USE  Northwest, Canadian@"
+"West (U.S.) --- n-usp@"
+"West Africa, Portuguese\n  USE  Angola@"
+"West Africa\n  USE  Africa, West@"
+"West Bank --- awba\n     Coded a-is (Israel) and/or a-jo (Jordan) before Mar. 1988@"
+"West Bank of the Jordan River\n  USE  West Bank@"
+"West Berlin\n  USE  Berlin (Germany)\n  for the western part of Germany:\n  USE  Germany (West)\n  for Germany as a whole:\n  USE  Germany@"
+"West Indies --- nw@"
+"West Indies, Dutch\n  USE  Netherlands Antilles@"
+"West Indies, French\n  Assigned code:\n     nwla --- Antilles, Lesser@"
+"West Irian\n  USE  Irian Jaya (Indonesia)@"
+"West New Guinea\n  USE  Irian Jaya (Indonesia)@"
+"West Pakistan\n  USE  Pakistan@"
+"West River (China) --- a-ccs@"
+"West Spitsbergen (Norway)\n  USE  Spitsbergen Island (Norway)@"
+"West Virginia --- n-us-wv@"
+"Western Australia --- u-at-we@"
+"Western Canada\n  USE  Canada, Western@"
+"Western Europe\n  USE  Europe, Western@"
+"Western Hemisphere --- xd@"
+"Western Sahara --- f-ss@"
+"Western Samoa\n  USE  Samoa@"
+"Western Siberia (Russia)\n  USE  Siberia, Western (Russia)@"
+"Western Soviet Union\n  USE  Soviet Union, Western@"
+"Western States (U.S.)\n  USE  West (U.S.)@"
+"White Russia\n  USE  Belarus@"
+"Wight, Isle of (England)\n  USE  Isle of Wight (England)@"
+"Windward Islands --- nwwi@"
+"Wisconsin --- n-us-wi@"
+"Woodlark Islands (Papua New Guinea)\n  Assigned code:\n     a-pp --- Papua New Guinea@"
+"Wyoming n-us-wy@"
+"Yakutia (Russia)\n  USE  Sakha (Russia)@"
+"Yangtze River (China) --- a-ccg@"
+"Yap (Micronesia)\n  Assigned code:\n     pomi --- Micronesia (Federated States)@"
+"Yellow River (China) --- a-ccy@"
+"Yellow Sea --- ay@"
+"Yemen (People's Democratic Republic)\n     Coded a-ys (Yemen (People's Democratic Republic) before Oct. 1992\n  USE  Yemen@"
+"Yemen --- a-ye@"
+"Yemen Arab Republic\n  USE  Yemen@"
+"Yugoslavia --- e-yu@"
+"Yukon Territory --- n-cn-yk@"
+"Yunnan Province (China) --- a-cc-yu@"
+"Zaire\n  USE  Congo (Democratic Republic)@"
+"Zambezi River --- fz@"
+"Zambia --- f-za@"
+"Zanzibar\n  Assigned code:\n     f-tz --- Tanzania@"
+"Zimbabwe --- f-rh@"
+"ÍÀkutskaíà A.S.S.R. (Russia)\n  USE  Sakha (Russia)@"
+"Îles Comores\n  USE  Comoros@"
+"Îles Froides\n  USE  Prince Edward Islands@"
+"Îles Kerguelen\n  USE  Kerguelen Islands@"
+"Îles Marquises de Mendoça (French Polynesia)\n  USE  Marquesas Islands (French Polynesia)@"
+"Îles Saint-Pierre et Miquelon\n  USE  Saint Pierre and Miquelon@";
