var aacr="Alabama	Ala.@"
+"Alberta	Alta.@"
+"Arizona	Ariz.@"
+"Arkansas	Ark.@"
+"Australian Capital Territory	A.C.T.@"
+"British Columbia	B.C.@"
+"California	Calif.@"
+"Colorado	Colo.@"
+"Connecticut	Conn.@"
+"Delaware	Del.@"
+"District of Columbia	D.C.@"
+"Distrito Federal	D.F.@"
+"Florida	Fla.@"
+"Georgia	Ga.@"
+"Hawaii	T.H.@"
+"Illinois	Ill.@"
+"Indiana	Ind.@"
+"Kansas	Kan.@"
+"Kentucky	Ky.@"
+"Louisiana	La.@"
+"Maine	Me.@"
+"Manitoba	Man.@"
+"Maryland	Md.@"
+"Massachusetts	Mass.@"
+"Michigan	Mich.@"
+"Minnesota	Minn.@"
+"Mississippi	Miss.@"
+"Missouri	Mo.@"
+"Montana	Mont.@"
+"Nebraska	Neb.@"
+"Nevada	Nev.@"
+"New Brunswick	N.B.@"
+"New Hampshire	N.H.@"
+"New Jersey	N.J.@"
+"New Mexico	N.M.@"
+"New South Wales	N.S.W.@"
+"New York	N.Y.@"
+"New Zealand	N.Z.@"
+"Newfoundland	Nfld.@"
+"North Carolina	N.C.@"
+"North Dakota	N.D.@"
+"Northern Territory	N.T.@"
+"Northwest Territories	N.W.T.@"
+"Nova Scotia	N.S.@"
+"Oklahoma	Okla.@"
+"Ontario	Ont.@"
+"Oregon	Or.@"
+"Pennsylvania	Pa.@"
+"Prince Edward Island	P.E.I.@"
+"Puerto Rico	P.R.@"
+"Queensland	Qld.@"
+"Rhode Island	R.I.@"
+"Russian Soviet Federated Socialist Republic	R.S.F.S.R.@"
+"Saskatchewan	Sask.@"
+"South Australia	S. Aust.@"
+"South Carolina	S.C.@"
+"South Dakota	S.D.@"
+"Tasmania	Tas.@"
+"Tennessee	Tenn.@"
+"Texas	Tex.@"
+"Union of Soviet Socialist Republics	U.S.S.R.@"
+"United Kingdom	U.K.@"
+"United States	U.S.@"
+"Vermont	Vt.@"
+"Victoria	Vic.@"
+"Virgin Islands	V.I.@"
+"Virginia	Va.@"
+"Washington	Wash.@"
+"West Virginia	W. Va.@"
+"Western Australia	W.A.@"
+"Wisconsin	Wis.@"
+"Wyoming	Wyo.@"
+"Yukon Territory	Yukon@"
+"aastakaik	aastak@"
+"Abdruck	abdr.@"
+"abgedruckt	abgedr.@"
+"Abteilung, Abtheilung	Abt.@"
+"accompaniment	acc.@"
+"afdeling	afd.@"
+"aflevering	afl.@"
+"altitude	alt.@"
+"alto	A@"
+"and	&@"
+"and others	et al.@"
+"Anno Domini	A.D.@"
+"approximately	approx.@"
+"argang	arg.@"
+"argraffiad	arg.@"
+"arranged	arr.@"
+"arranger	arr.@"
+"atdolgozott	atdolg.@"
+"Auflage	Aufl.@"
+"augmente, -e	augm.@"
+"augmented	aug.@"
+"aumentada	aum.@"
+"aumentato	aum.@"
+"Ausgabe	Ausg.@"
+"avdeling	avd.@"
+"Band	Bd.@"
+"band	bd.@"
+"Bandchen	Bdchn.@"
+"Bande	Bde.@"
+"baritone	Bar@"
+"bass	B@"
+"Before Christ	B.C.@"
+"bilangan	bil.@"
+"binary coded decimal	BCD@"
+"bind	bd.@"
+"black and white	b&w@"
+"bogtrykkeri	bogtr.@"
+"boktrykkeri	boktr.@"
+"book	bk.@"
+"born	b.@"
+"bovitett	bov.@"
+"broj	br.@"
+"Brother, -s	Bro., Bros.@"
+"Buchdrucker, -ei	Buchdr.@"
+"Buchhandlung	Buchh.@"
+"bulletin	bull.@"
+"bytes per inch	bpi@"
+"capitolo	cap.@"
+"cast	c.@"
+"centimetre, -s	cm.@"
+"century	cent.@"
+"cetakan	cet.@"
+"chapter	ch.@"
+"circa	ca.@"
+"cislo	cis.@"
+"colored, coloured	col.@"
+"Compagnia	Cia.@"
+"Compagnie	Cie@"
+"Compania	Cia.@"
+"Company	Co.@"
+"compare	cf.@"
+"compiler	comp.@"
+"confer	cf.@"
+"copyright	c@"
+"Corporation	Corp.@"
+"corrected	corr.@"
+"corregido	corr.@"
+"corretto, -a	corr.@"
+"corrige, -e	corr.@"
+"czesc	cz.@"
+"declination	decl.@"
+"deel	d.@"
+"del (Danish, Norwegian, Swedish)	d.@"
+"departement	dep.@"
+"Department	Dept.@"
+"diameter	diam.@"
+"died	d.@"
+"diena	d.@"
+"djilid	djil.@"
+"document	doc.@"
+"dopunjeno	dop.@"
+"drukarnia	druk.@"
+"edicion	ed.@"
+"edition, -s	ed., eds.@"
+"editor	ed.@"
+"edizione	ed.@"
+"enlarged	enl.@"
+"equinox	eq.@"
+"erganzt	erg.@"
+"erweitert	erw.@"
+"establecimiento tipografico	estab. tip.@"
+"et alii	et al.@"
+"et cetera	etc.@"
+"evfolyam	evf.@"
+"facsimile, -s	facsim., facsims.@"
+"fascicle	fasc.@"
+"fascicule	fasc.@"
+"flourished	fl.@"
+"folio	fol.@"
+"following	ff.@"
+"foot, feet	ft.@"
+"frame, -s	fr.@"
+"frames per second	fps@"
+"fratelli	f.lli@"
+"Gebruder	Gebr.@"
+"gedruckt	gedr.@"
+"genealogical	geneal.@"
+"godina	g.@"
+"government	govt.@"
+"Government Printing Office	G.P.O.@"
+"Handschrift, -en	Hs., Hss.@"
+"Her (His) Majesty's Stationery Office	H.M.S.O.@"
+"Hermanos	Hnos.@"
+"hour, -s	hr.@"
+"id est	i.e.@"
+"Idus	Id.@"
+"illustration	ill.@"
+"illustrator	ill.@"
+"imienia	im.@"
+"imprenta	impr.@"
+"imprimerie	impr.@"
+"inch, -es	in.@"
+"inches per second	ips@"
+"including	incl.@"
+"Incorporated	Inc.@"
+"introduction	introd.@"
+"izdaja	izd.@"
+"izmenjeno	izm.@"
+"jaargang	jaarg.@"
+"Jahrgang	Jahrg.@"
+"javitott	jav.@"
+"jilid	jil.@"
+"Kalendae	Kal.@"
+"kiadas	kiad.@"
+"kilometre, -s	km.@"
+"kniha	kn.@"
+"knjiga	knj.@"
+"kotet	kot.@"
+"ksiegarnia	ksieg.@"
+"leto	l.@"
+"librarie	libr.@"
+"Lieferung	Lfg.@"
+"Limited	Ltd.@"
+"livraison	livr.@"
+"maatschappij	mij.@"
+"manuscript, -s	ms., mss.@"
+"menuo	men.@"
+"metai	m.@"
+"metre, -s	m.@"
+"mezzo-soprano	Mz@"
+"miesiecznik	mies.@"
+"millimetre, -s	mm.@"
+"minute, -s	min.@"
+"miscellaneous	misc.@"
+"monophonic	mono.@"
+"Nachfolger	Nachf.@"
+"naklad	nakl.@"
+"nakladatelstvi	nakl.@"
+"naukowy	nauk.@"
+"neue Folge	n.F.@"
+"new series	new ser.@"
+"New Testament	N.T.@"
+"no name (of publisher)	s.n.@"
+"no place (of publication)	s.l.@"
+"nombor	no.@"
+"nomor	no.@"
+"Nonae	Non.@"
+"nouveau, nouvelle	nouv.@"
+"number, -s	no.@"
+"numbered	numb.@"
+"numer	nr.@"
+"numero (Finnish)	n:o@"
+"numero (French)	no@"
+"numero (Italian)	n.@"
+"numero (Spanish)	no.@"
+"Nummer	Nr.@"
+"nummer	nr.@"
+"nuovamente	nuov.@"
+"odbitka	obd.@"
+"oddzial	oddz.@"
+"Old Testament	O.T.@"
+"omarbeidet	omarb.@"
+"oplag	opl.@"
+"opplag	oppl.@"
+"opracowane	oprac.@"
+"opus	op.@"
+"otisk	it.@"
+"page, -s	p.@"
+"paperback	pbk.@"
+"part, -s	pt., pts.@"
+"parte	pt.@"
+"partie, -s	ptie, pties@"
+"phonogram (copyright)	p@"
+"photograph, -s	photo., photos.@"
+"plate number, -s	pl. no.@"
+"poprawione	popr.'@"
+"portrait, -s	port., ports.@"
+"posthumous	posth.@"
+"predelan	pred.@"
+"preface	pref.@"
+"preliminary	prelim.@"
+"printing	print.@"
+"privately printed	priv. print.@"
+"projection	proj.@"
+"prosiren	pros.@"
+"przeklad	przekl.@"
+"przerobione	przerob.@"
+"pseudonym	pseud.@"
+"publishing	pub.@"
+"quadraphonic	quad.@"
+"redakcja	red.@"
+"refondu, -e	ref.@"
+"reimpression	reimpr.@"
+"report	rept.@"
+"reprinted	repr.@"
+"reproduced	reprod.@"
+"reviderade	revid.@"
+"revise, -e	rev.@"
+"revised	rev.@"
+"revolutions per minute	rpm@"
+"revu, -e	rev.@"
+"right ascension	RA@"
+"riveduto	riv.@"
+"rocnik	roc.@"
+"rocznik	rocz.@"
+"rok	r.@"
+"rozszerzone	rozsz.@"
+"second, -s	sec.@"
+"serie	ser.@"
+"series	ser.@"
+"sesit	ses.@"
+"signature	sig.@"
+"silent	si.@"
+"sine loco	s.l.@"
+"sine nomine	s.n.@"
+"sklad glowny	skl. gl.@"
+"soprano	S@"
+"sound	sd.@"
+"stabilimento tipografico	stab. tip.@"
+"stereophonic	stereo.@"
+"stevilka	st.@"
+"stronica	str.@"
+"superintendent	supt.@"
+"Superintendent of Documents	Supt. of Docs.@"
+"supplement	suppl.@"
+"svazek	sv.@"
+"szam	sz.@"
+"tahun	th.@"
+"talleres graficos	tall. graf.@"
+"Teil, Theil	T.@"
+"tenor	T@"
+"tipografia, tipografica	tip.@"
+"tiskarna	tisk.@"
+"title page	t.p.@"
+"tjetakan	tjet.@"
+"tome	t.@"
+"tomo	t.@"
+"towarzystwo	tow.@"
+"translator	tr.@"
+"typographical	typog.@"
+"typographie, typographique	typ.@"
+"udarbejdet	udarb.@"
+"udgave	udg.@"
+"udgivet	udg.@"
+"uitgaaf	uitg.@"
+"uitgegeven	uitg.@"
+"uitgevers	uitg.@"
+"umgearbeitet	umgearb.@"
+"unaccompanied	unacc.@"
+"Universitats-Buchdrucker, -ei	Univ.-Buchdr.@"
+"upplaga	uppl.@"
+"utarbeidet	utarb.@"
+"utgave	utg.@"
+"utgiven	utg.@"
+"uzupelnione	uzup.@"
+"verbesserte	verb.@"
+"vermehrte	verm.@"
+"volume, -s	v.@"
+"volume, -s (before Roman numerals)	vol., vols.@"
+"vuosikerta	vuosik.@"
+"vydani	vyd.@"
+"wydanie	wyd.@"
+"wydawnictwo	wydawn.@"
+"wydzial	wydz.@"
+"zalozba	zal.@"
+"zeszyt	zesz.@"
+"zvazok	zv.@"
+"zvezek	zv.@";
