var country="aa	Albania@"
+"abc	Alberta@"
+"[discontinued code]  ac	Ashmore and Cartier Islands@"
+"ae	Algeria@"
+"af	Afghanistan@"
+"ag	Argentina@"
+"[discontinued code]  ai	Anguilla@"
+"ai	Armenia (Republic)@"
+"[discontinued code]  air	Armenian S.S.R.@"
+"aj	Azerbaijan@"
+"[discontinued code]  ajr	Azerbaijan S.S.R.@"
+"aku	Alaska@"
+"alu	Alabama@"
+"am	Anguilla@"
+"an	Andorra@"
+"ao	Angola@"
+"aq	Antigua and Barbuda@"
+"aru	Arkansas@"
+"as	American Samoa@"
+"at	Australia@"
+"au	Austria@"
+"aw	Aruba@"
+"ay	Antarctica@"
+"azu	Arizona@"
+"ba	Bahrain@"
+"bb	Barbados@"
+"bcc	British Columbia@"
+"bd	Burundi@"
+"be	Belgium@"
+"bf	Bahamas@"
+"bg	Bangladesh@"
+"bh	Belize@"
+"bi	British Indian Ocean Territory@"
+"bl	Brazil@"
+"bm	Bermuda Islands@"
+"bn	Bosnia and Herzegovina@"
+"bo	Bolivia@"
+"bp	Solomon Islands@"
+"br	Burma@"
+"bs	Botswana@"
+"bt	Bhutan@"
+"bu	Bulgaria@"
+"bv	Bouvet Island@"
+"bw	Belarus@"
+"[discontinued code]  bwr	Byelorussian S.S.R.@"
+"bx	Brunei@"
+"cau	California@"
+"cb	Cambodia@"
+"cc	China@"
+"cd	Chad@"
+"ce	Sri Lanka@"
+"cf	Congo (Brazzaville)@"
+"cg	Congo (Democratic Republic)@"
+"ch	China (Republic : 1949- )@"
+"ci	Croatia@"
+"cj	Cayman Islands@"
+"ck	Colombia@"
+"cl	Chile@"
+"cm	Cameroon@"
+"[discontinued code]  cn	Canada@"
+"cou	Colorado@"
+"[discontinued code]  cp	Canton and Enderbury Islands@"
+"cq	Comoros@"
+"cr	Costa Rica@"
+"[discontinued code]  cs	Czechoslovakia@"
+"ctu	Connecticut@"
+"cu	Cuba@"
+"cv	Cape Verde@"
+"cw	Cook Islands@"
+"cx	Central African Republic@"
+"cy	Cyprus@"
+"[discontinued code]  cz	Canal Zone@"
+"dcu	District of Columbia@"
+"deu	Delaware@"
+"dk	Denmark@"
+"dm	Benin@"
+"dq	Dominica@"
+"dr	Dominican Republic@"
+"em	East Timor@"
+"ea	Eritrea@"
+"ec	Ecuador@"
+"eg	Equatorial Guinea@"
+"enk	England@"
+"er	Estonia@"
+"[discontinued code]  err	Estonia@"
+"es	El Salvador@"
+"et	Ethiopia@"
+"fa	Faroe Islands@"
+"fg	French Guiana@"
+"fi	Finland@"
+"fj	Fiji@"
+"fk	Falkland Islands@"
+"flu	Florida@"
+"fm	Micronesia (Federated States)@"
+"fp	French Polynesia@"
+"fr	France@"
+"fs	Terres australes et antarctiques françaises@"
+"ft	Djibouti@"
+"gau	Georgia@"
+"gb	Kiribati@"
+"gd	Grenada@"
+"[discontinued code]  ge	Germany (East)@"
+"gh	Ghana@"
+"gi	Gibraltar@"
+"gl	Greenland@"
+"gm	Gambia@"
+"[discontinued code]  gn	Gilbert and Ellice Islands@"
+"go	Gabon@"
+"gp	Guadeloupe@"
+"gr	Greece@"
+"gs	Georgia (Republic)@"
+"[discontinued code]  gsr	Georgian S.S.R.@"
+"gt	Guatemala@"
+"gu	Guam@"
+"gv	Guinea@"
+"gw	Germany@"
+"gy	Guyana@"
+"gz	Gaza Strip@"
+"hiu	Hawaii@"
+"[discontinued code]  hk	Hong Kong@"
+"hm	Heard and McDonald Islands@"
+"ho	Honduras@"
+"ht	Haiti@"
+"hu	Hungary@"
+"iau	Iowa@"
+"ic	Iceland@"
+"idu	Idaho@"
+"ie	Ireland@"
+"ii	India@"
+"ilu	Illinois@"
+"inu	Indiana@"
+"io	Indonesia@"
+"iq	Iraq@"
+"ir	Iran@"
+"is	Israel@"
+"it	Italy@"
+"[discontinued code]  iu	Israel-Syria Demilitarized Zones@"
+"iv	Côte d'Ivoire@"
+"[discontinued code]  iw	Israel-Jordan Demilitarized Zones@"
+"iy	Iraq-Saudi Arabia Neutral Zone@"
+"ja	Japan@"
+"ji	Johnston Atoll@"
+"jm	Jamaica@"
+"[discontinued code]  jn	Jan Mayen@"
+"jo	Jordan@"
+"ke	Kenya@"
+"kg	Kyrgyzstan@"
+"[discontinued code]  kgr	Kirghiz S.S.R.@"
+"kn	Korea (North)@"
+"ko	Korea (South)@"
+"kv	Kosovo@"
+"ksu	Kansas@"
+"ku	Kuwait@"
+"kyu	Kentucky@"
+"kz	Kazakhstan@"
+"[discontinued code]  kzr	Kazakh S.S.R.@"
+"lau	Louisiana@"
+"lb	Liberia@"
+"le	Lebanon@"
+"lh	Liechtenstein@"
+"li	Lithuania@"
+"[discontinued code]  lir	Lithuania@"
+"[discontinued code]  ln	Central and Southern Line Islands@"
+"lo	Lesotho@"
+"ls	Laos@"
+"lu	Luxembourg@"
+"lv	Latvia@"
+"[discontinued code]  lvr	Latvia@"
+"ly	Libya@"
+"mau	Massachusetts@"
+"mbc	Manitoba@"
+"mc	Monaco@"
+"mdu	Maryland@"
+"meu	Maine@"
+"mf	Mauritius@"
+"mg	Madagascar@"
+"mh	Macao@"
+"miu	Michigan@"
+"mj	Montserrat@"
+"mk	Oman@"
+"ml	Mali@"
+"mm	Malta@"
+"mnu	Minnesota@"
+"mo	Montenegro@"
+"mou	Missouri@"
+"mp	Mongolia@"
+"mq	Martinique@"
+"mr	Morocco@"
+"msu	Mississippi@"
+"mtu	Montana@"
+"mu	Mauritania@"
+"mv	Moldova@"
+"[discontinued code]  mvr	Moldavian S.S.R.@"
+"mw	Malawi@"
+"mx	Mexico@"
+"my	Malaysia@"
+"mz	Mozambique@"
+"na	Netherlands Antilles@"
+"nbu	Nebraska@"
+"ncu	North Carolina@"
+"ndu	North Dakota@"
+"ne	Netherlands@"
+"nfc	Newfoundland and Laborador@"
+"ng	Niger@"
+"nhu	New Hampshire@"
+"nik	Northern Ireland@"
+"nju	New Jersey@"
+"nkc	New Brunswick@"
+"nl	New Caledonia@"
+"[discontinued code]  nm	Northern Mariana Islands@"
+"nmu	New Mexico@"
+"nn	Vanuatu@"
+"no	Norway@"
+"np	Nepal@"
+"nq	Nicaragua@"
+"nr	Nigeria@"
+"nsc	Nova Scotia@"
+"ntc	Northwest Territories@"
+"nu	Nauru@"
+"nvu	Nevada@"
+"nw	Northern Mariana Islands@"
+"nx	Norfolk Island@"
+"nyu	New York (State)@"
+"nz	New Zealand@"
+"ohu	Ohio@"
+"oku	Oklahoma@"
+"onc	Ontario@"
+"oru	Oregon@"
+"ot	Mayotte@"
+"pau	Pennsylvania@"
+"pc	Pitcairn Island@"
+"pe	Peru@"
+"pf	Paracel Islands@"
+"pg	Guinea-Bissau@"
+"ph	Philippines@"
+"pic	Prince Edward Island@"
+"pk	Pakistan@"
+"pl	Poland@"
+"pn	Panama@"
+"po	Portugal@"
+"pp	Papua New Guinea@"
+"pr	Puerto Rico@"
+"[discontinued code]  pt	Portuguese Timor@"
+"pw	Palau@"
+"py	Paraguay@"
+"qa	Qatar@"
+"quc	Québec (Province)@"
+"re	Réunion@"
+"rb	Serbia@"
+"rh	Zimbabwe@"
+"riu	Rhode Island@"
+"rm	Romania@"
+"ru	Russia (Federation)@"
+"[discontinued code]  rur	Russian S.F.S.R.@"
+"rw	Rwanda@"
+"[discontinued code]  ry	Ryukyu Islands, Southern@"
+"sa	South Africa@"
+"[discontinued code]  sb	Svalbard@"
+"scu	South Carolina@"
+"sdu	South Dakota@"
+"se	Seychelles@"
+"sf	Sao Tome and Principe@"
+"sg	Senegal@"
+"sh	Spanish North Africa@"
+"si	Singapore@"
+"sj	Sudan@"
+"[discontinued code]  sk	Sikkim@"
+"sl	Sierra Leone@"
+"sm	San Marino@"
+"snc	Saskatchewan@"
+"so	Somalia@"
+"sp	Spain@"
+"sq	Swaziland@"
+"sr	Surinam@"
+"ss	Western Sahara@"
+"stk	Scotland@"
+"su	Saudi Arabia@"
+"[discontinued code]  sv	Swan Islands@"
+"sw	Sweden@"
+"sx	Namibia@"
+"sy	Syria@"
+"sz	Switzerland@"
+"ta	Tajikistan@"
+"[discontinued code]  tar	Tajik S.S.R.@"
+"tc	Turks and Caicos Islands@"
+"tg	Togo@"
+"th	Thailand@"
+"ti	Tunisia@"
+"tk	Turkmenistan@"
+"[discontinued code]  tkr	Turkmen S.S.R.@"
+"tl	Tokelau@"
+"tnu	Tennessee@"
+"to	Tonga@"
+"tr	Trinidad and Tobago@"
+"ts	United Arab Emirates@"
+"[discontinued code]  tt	Trust Territory of the Pacific Islands@"
+"tu	Turkey@"
+"tv	Tuvalu@"
+"txu	Texas@"
+"tz	Tanzania@"
+"ua	Egypt@"
+"uc	United States Misc. Caribbean Islands@"
+"ug	Uganda@"
+"[discontinued code]  ui	United Kingdom Misc. Islands@"
+"uik	United Kingdom Misc. Islands@"
+"[discontinued code]  uk	United Kingdom@"
+"un	Ukraine@"
+"[discontinued code]  unr	Ukraine@"
+"up	United States Misc. Pacific Islands@"
+"[discontinued code]  ur	Soviet Union@"
+"[discontinued code]  us	United States@"
+"utu	Utah@"
+"uv	Burkina Faso@"
+"uy	Uruguay@"
+"uz	Uzbekistan@"
+"[discontinued code]  uzr	Uzbek S.S.R.@"
+"vau	Virginia@"
+"vb	British Virgin Islands@"
+"vc	Vatican City@"
+"ve	Venezuela@"
+"vi	Virgin Islands of the United States@"
+"vm	Vietnam@"
+"[discontinued code]  vn	Vietnam, North@"
+"vp	Various places@"
+"[discontinued code]  vs	Vietnam, South@"
+"vtu	Vermont@"
+"wau	Washington (State)@"
+"[discontinued code]  wb	West Berlin@"
+"wf	Wallis and Futuna@"
+"wiu	Wisconsin@"
+"wj	West Bank of the Jordan River@"
+"wk	Wake Island@"
+"wlk	Wales@"
+"ws	Samoa@"
+"wvu	West Virginia@"
+"wyu	Wyoming@"
+"xa	Christmas Island (Indian Ocean)@"
+"xb	Cocos (Keeling) Islands@"
+"xc	Maldives@"
+"xd	Saint Kitts-Nevis@"
+"xe	Marshall Islands@"
+"xf	Midway Islands@"
+"xh	Niue@"
+"[discontinued code]  xi	Saint Kitts-Nevis-Anguilla@"
+"xj	Saint Helena@"
+"xk	Saint Lucia@"
+"xl	Saint Pierre and Miquelon@"
+"xm	Saint Vincent and the Grenadines@"
+"xn	Macedonia@"
+"xo	Slovakia@"
+"xp	Spratly Island@"
+"xr	Czech Republic@"
+"xs	South Georgia and the South Sandwich Islands@"
+"xv	Slovenia@"
+"xx	No place, unknown, or undetermined@"
+"xxc	Canada@"
+"xxk	United Kingdom@"
+"[discontinued code]  xxr	Soviet Union@"
+"xxu	United States@"
+"ye	Yemen@"
+"ykc	Yukon Territory@"
+"[discontinued code]  ys	Yemen (People's Democratic Republic)@"
+"yu	Yugoslavia@"
+"za	Zambia@"
+"nuc	Nunavut@";
