var geogcutter="Abyssinia	 see Ethiopia@"
+"Adair, Camp (local OSU Cutter)	A3@"
+"Afghanistan	A3@"
+"Africa	A35@"
+"Africa, Central	A352@"
+"Africa, East	A353@"
+"Africa, Eastern	A354@"
+"Africa, French-Speaking West	A3545@"
+"Africa, North	A355@"
+"Africa, Northeast	A3553@"
+"Africa, Northwest	A3554@"
+"Africa, South	 see South Africa@"
+"Africa, Southern	A356@"
+"Africa, Sub-Saharan	A357@"
+"Africa, West	A358@"
+"Alabama	A2@"
+"Alaska	A4@"
+"Albania	A38@"
+"Albany (local OSU Cutter)	A4@"
+"Alberta	A3@"
+"Algeria	A4@"
+"Alpine (local OSU Cutter)	A46@"
+"Alps	A43@"
+"America	A45@"
+"American Samoa	A46@"
+"Amity (local OSU Cutter)	A49@"
+"Andorra	A48@"
+"Angola	A5@"
+"Anguilla	A54@"
+"Antarctica	A6@"
+"Antigua and Barbuda	A63@"
+"Antigua	 see Antigua and Barbuda@"
+"Arab countries	A65@"
+"Arctic regions	A68@"
+"Argentina	A7@"
+"Arizona	A6@"
+"Arkansas	A8@"
+"Armenia	A75@"
+"Armenia (Republic)	A76@"
+"Aruba	A77@"
+"Ashland (local OSU Cutter)	A8@"
+"Asia	A78@"
+"Asia, Central	A783@"
+"Asia, East	 see East Asia@"
+"Asia, South	 see South Asia@"
+"Asia, Southeastern	A785@"
+"Asia, Southwestern	 see Middle East@"
+"Astoria district (local OSU Cutter)	 (local OSU Cutter)	N61:3A8@"
+"Astoria (local OSU Cutter)	 (local OSU Cutter)	A85@"
+"Australasia	A788@"
+"Australia	A8@"
+"Austria	A9@"
+"Azerbaijan	A98@"
+"Bahamas	B24@"
+"Bahrain	B26@"
+"Baker district (BLM) (local OSU Cutter)	B3@"
+"Baker/Baker City (local OSU Cutter)	B3@"
+"Balkan Peninsula	B28@"
+"Baltic States	B29@"
+"Bangladesh	B3@"
+"Barbados	B35@"
+"Barbuda	 see Antigua and Barbuda@"
+"Barlow Road (West Linn) (local OSU Cutter)	B37@"
+"Basin & Range province (local OSU Cutter)	B385@"
+"Basin grazing district (local OSU Cutter)	B38@"
+"Beaverton (local OSU Cutter)	B4@"
+"Belarus	B38@"
+"Belgium	B4@"
+"Belize	B42@"
+"Bend (local OSU Cutter)	B44@"
+"Benelux Countries	B425@"
+"Bengal	B43@"
+"Benin	B45@"
+"Bermuda	B46@"
+"Bhutan	B47@"
+"Bolivia	B5@"
+"Bonaire	B52@"
+"Bosnia and Herzegovina	B54@"
+"Botswana	B55@"
+"Bowen Valley (local OSU Cutter)	B6 @"
+"Brazil	B6@"
+"British Columbia	B8@"
+"British Guiana	 see Guyana@"
+"British Honduras	 see Belize@"
+"British Isles	B65@"
+"Brookings/Brookings Harbor (local OSU Cutter)	B7@"
+"Brothers planning area (local OSU Cutter)	B7@"
+"Brunei	B7@"
+"Bulgaria	B9@"
+"Bull of the Woods Wilderness area (local OSU Cutter)	B85@"
+"Bullrun Rock (local OSU Cutter)	B8@"
+"Burkina Faso	B92@"
+"Burma	B93@"
+"Burns district (local OSU Cutter)	B82@"
+"Burns (local OSU Cutter)	B8@"
+"Burundi	B94@"
+"Byzantine Empire	B97@"
+"California	C2@"
+"Cambodia	C16@"
+"Cameroon	C17@"
+"Canada	C2@"
+"Canary Islands	C23@"
+"Canby (local OSU Cutter)	C2@"
+"Canyonville area (local OSU Cutter)	C34@"
+"Canyonville (local OSU Cutter)	C36@"
+"Cape Verde	C25@"
+"Caribbean Area	C27@"
+"Caroline Islands	C275@"
+"Cascade Mountain Range (local OSU Cutter)	C35@"
+"Cascade Range forest reserve (local OSU Cutter)	C3@"
+"Caucasus	C28@"
+"Cayman Islands	C29@"
+"Central African Republic	C33@"
+"Central America	C35@"
+"Central Europe	see Europe, Central        @"
+"Central Oregon (local OSU Cutter)	C45@"
+"Ceylon	 see Sri Lanka@"
+"Chad	C45@"
+"Channel Islands	C48@"
+"Chetco Basin (local OSU Cutter)	C5@"
+"Chile	C5@"
+"China	C6@"
+"Clackamas-Marion fire protection  (local OSU Cutter)	C57district@"
+"Coast (local OSU Cutter)	C6@"
+"Colombia	C7@"
+"Colorado	C6@"
+"Columbia Gorge Nat'l Scenic Area (local OSU Cutter)	C635@"
+"Columbia Gorge (local OSU Cutter)	C63@"
+"Columbia Wilderness Area (local OSU Cutter)	C638@"
+"Commonwealth countries	C723@"
+"Communist countries	C725@"
+"Comoros	C73@"
+"Congo (Brazzaville)	C74@"
+"Connecticut	C8@"
+"Cook Islands	C76@"
+"Coos Bay area (local OSU Cutter)	C66@"
+"Coos Bay (local OSU Cutter)	C5@"
+"Coos fire protection district (local OSU Cutter)	C67@"
+"Corvallis (local OSU Cutter)	C6@"
+"Costa Rica	C8@"
+"Côte d'Ivoire	C85@"
+"Craig Mountain Cone area (local OSU Cutter)	C71@"
+"Crater Lake (.) (local OSU Cutter)	C74@"
+"Crater Lake (local OSU Cutter)	C73@"
+"Croatia	C87@"
+"Crooked River grazing district (local OSU Cutter)	C76@"
+"Cuba	C9@"
+"Curaçao	C92@"
+"Cyprus	C93@"
+"Czech Republic	C94@"
+"Czechoslovakia	C95@"
+"Dahomey	 see Benin@"
+"Dallas (local OSU Cutter)	D34@"
+"Dalles area (local OSU Cutter)	D34@"
+"Dalles City (historic The Dalles) (local OSU Cutter)	D35@"
+"Delaware	D3@"
+"Denmark	D4@"
+"Deschutes drainage basin (local OSU Cutter)	D45@"
+"Deschutes National Forest (local OSU Cutter)	D48@"
+"Deschutes River area (local OSU Cutter)	D49@"
+"Desert Trail (local OSU Cutter)	D4@"
+"Developing countries	D44@"
+"Diamond Peak Wilderness (local OSU Cutter)	D5@"
+"District of Columbia	 see Washington (D.C.)@"
+"Djibouti	D5@"
+"Dominica	D6@"
+"Dominican Republic	D65@"
+"Douglas fire protection district (local OSU Cutter)	D6@"
+"Drain-Yoncalla area (local OSU Cutter)	D7@"
+"Drift Creek (local OSU Cutter)	D75@"
+"Dutch East Indies	 see Indonesia@"
+"Dutch Guiana	 see Surinam@"
+"Eagle Cap Wilderness (local OSU Cutter)	E23@"
+"East Asia	E18@"
+"Eastern Oregon protection district (local OSU Cutter)	E237@"
+"Ecuador	E2@"
+"Egypt	E3@"
+"El Salvador	 see Salvador@"
+"Ellice Islands	 see Tuvalu@"
+"England	 see Great Britain@"
+"Eola Hills area (local OSU Cutter)	 (local OSU Cutter)	E6@"
+"Equatorial Guinea	E6@"
+"Eritrea	E65@"
+"Estonia	E75@"
+"Ethiopia	E8@"
+"Eugene district (local OSU Cutter)	E8@"
+"Eugene/Eugene-Springfield (local OSU Cutter)	E8@"
+"Eurasia	E83@"
+"Europe	E85@"
+"Europe, Central	 C36@"
+"Europe, Eastern	E852@"
+"Europe, Northern	E853@"
+"Europe, Southern	E854@"
+"Europe, Western	 see Europe@"
+"European Economic Community countries	E86@"
+"European Free Trade Association countries	E87@"
+"European Union countries	 see Europe@"
+"Falkland Islands	F3@"
+"Faroe Islands	F32@"
+"Fiji Islands	F4@"
+"Finland	F5@"
+"Florida	F6@"
+"Forest Grove unit (local OSU Cutter)	N61:3F6@"
+"Forest Grove (local OSU Cutter)	F6@"
+"Former Soviet republics	F6@"
+"Formosa	 see Taiwan@"
+"Fort Stevens area (local OSU Cutter)	F6@"
+"France	F8@"
+"Fremont National Forest (local OSU Cutter)	F74@"
+"French Guiana	F9@"
+"French Polynesia	F93@"
+"Gabon	G2@"
+"Galapagos Islands	G23@"
+"Gambia	G25@"
+"Georgia	G4@"
+"Georgia (Republic)	G28@"
+"Germany	G3@"
+"German Democratic Republic	 see Germany@"
+"East Germany	 see Germany@"
+"Federal Republic of Germany	 see Germany@"
+"West Germany	 see Germany@"
+"Ghana	G4@"
+"Gibraltar	G5@"
+"Gilbert Islands	 see Kiribati@"
+"Glenddale quad (local OSU Cutter)	G54@"
+"Gold Beach area (local OSU Cutter)	G65@"
+"Goose & Summer Lakes basin (local OSU Cutter)	G68@"
+"Goose Lake basin (local OSU Cutter)	G681@"
+"Grande Ronde drainage basin (local OSU Cutter)	G7@"
+"Grande Ronde Valley area (local OSU Cutter)	G75@"
+"Grants Pass area (local OSU Cutter)	G73@"
+"Grants Pass (local OSU Cutter)	G7@"
+"Great Britain	G7@"
+"Greece	G8@"
+"Greenland	G83@"
+"Grenada	G84@"
+"Guadeloupe	G845@"
+"Guam	G85@"
+"Guatemala	G9@"
+"Guiana	G915@"
+"Guinea	G92@"
+"Guinea-Bissau	G93@"
+"Guyana	G95@"
+"Haiti	H2@"
+"Harney basin (local OSU Cutter)	H3@"
+"Hawaii	H3@"
+"Hispaniola	H55@"
+"Holland	 see Netherlands@"
+"Honduras	H8@"
+"Hong Kong	H85@"
+"Hood River drainage basin (local OSU Cutter)	H6@"
+"Hungary	H9@"
+"Iceland	I2@"
+"Idaho	I2@"
+"Illinois	I3@"
+"India	I4@"
+"Indiana	I6@"
+"Indochina	I48@"
+"Indonesia	I5@"
+"Inner Mongolia	 see China@"
+"Iowa	I8@"
+"Iran	I7@"
+"Iraq	I72@"
+"Ireland	I73@"
+"Islamic countries	I74@"
+"Islamic Empire	I742@"
+"Islands of the Indian Ocean	I743@"
+"Israel	I75@"
+"Italy	I8@"
+"Ivory Coast,	 see Côte d'Ivoire@"
+"Jackson area (local OSU Cutter)	M2:2J3@"
+"Jackson forest (local OSU Cutter)	J3@"
+"Jacksonville (local OSU Cutter)	J3@"
+"Jamaica	J25@"
+"Japan	J3@"
+"Java	 see Indonesia@"
+"Jerusalem	J4@"
+"John Day drainage basin (local OSU Cutter)	J65@"
+"John Day River (local OSU Cutter)	J67@"
+"John Day (local OSU Cutter)	J6@"
+"Jordan	J6@"
+"Jugoslavia	 see Yugoslavia@"
+"Jutland	 see Denmark@"
+"Kalmiopsis Wilderness (local OSU Cutter)	K3@"
+"Kampuchea	 see Cambodia@"
+"Kansas	K2@"
+"Kazakhstan	K3@"
+"Keating (local OSU Cutter)	K4@"
+"Kentucky	K4@"
+"Kenya	K4@"
+"Kerguelen Islands	K43@"
+"Kiribati	K5@"
+"Klamath drainage basin (local OSU Cutter)	K55@"
+"Klamath Falls area (local OSU Cutter)	K52@"
+"Klamath Falls (local OSU Cutter)	K55@"
+"Klamath-Lake forest protection district (local OSU Cutter)	K55@"
+"Korea	K6@"
+"Korea (Democratic People's Republic)	 see Korea (North)@"
+"Korea (North)	K7@"
+"Korea (Republic)	 see Korea@"
+"Korea (South)	 see Korea@"
+"Kosovo	 K6@"
+"Kuwait	K9@"
+"Kyrgyzstan	K98@"
+"La Grande (local OSU Cutter)	L33@"
+"Lakeview district (BLM) (local OSU Cutter)	L3@"
+"Lane forest protection district (local OSU Cutter)	L34@"
+"Langlois (local OSU Cutter)	L38@"
+"Laos	L28@"
+"LaPine (local OSU Cutter)	L36@"
+"Latin America	L29@"
+"Latvia	L35@"
+"Lebanon	L4@"
+"Lebanon (local OSU Cutter)	L42@"
+"Lesotho	L5@"
+"Liberia	L7@"
+"Libya	L75@"
+"Liechtenstein	L76@"
+"Linn protection district (local OSU Cutter)	L5@"
+"Lithuania	L78@"
+"Lost Forest wilderness study area (local OSU Cutter)	L6@"
+"Louisiana	L8@"
+"Lower Willamette drainage basin (local OSU Cutter)	W54@"
+"Luxembourg	L9@"
+"Macao	M25@"
+"Macaronesia	M26@"
+"Macedonia	M27@"
+"Macedonia (Republic)	M275@"
+"Madagascar	M28@"
+"Madras (local OSU Cutter)	M31@"
+"Maine	M2@"
+"Malagasy Republic	 see Madagascar@"
+"Malawi	M3@"
+"Malay Archipelago	M35@"
+"Malaya	 see Malaysia@"
+"Malaysia	M4@"
+"Maldives	M415@"
+"Malheur Lake (local OSU Cutter)	M32@"
+"Malheur National Forest (local OSU Cutter)	M34@"
+"Malheur Project area (local OSU Cutter)	M31@"
+"Malheur River drainage basin (local OSU Cutter)	M3@"
+"Mali	M42@"
+"Malta	M43@"
+"Manitoba	M3@"
+"Marshall Islands	M433@"
+"Martinique	M435@"
+"Maryland	M3@"
+"Massachusetts	M4@"
+"Mauritania	M44@"
+"Mauritius	M45@"
+"McDonald Forest (local OSU Cutter)	M2@"
+"McKenzie River (local OSU Cutter)	M24@"
+"McMinnville (local OSU Cutter)	M35@"
+"Medford (local OSU Cutter)	M4@"
+"Melanesia	M5@"
+"Mexican-American Border Region	M58@"
+"Mexico	M6@"
+"Michigan	M5@"
+"Micronesia	M625@"
+"Mid-coast drainage basin (local OSU Cutter)	M5@"
+"Middle East	M628@"
+"Middle Willamette drainage basin (local OSU Cutter)	W53@"
+"Minnesota	M6@"
+"Mississippi	M7@"
+"Missouri	M8@"
+"Moldova	M629@"
+"Monaco	M63@"
+"Mongolia	M65@"
+"Mongolia (Mongolian People's Republic)	 see Mongolia@"
+"Monmouth (local OSU Cutter)	M75@"
+"Montana	M9@"
+"Montenegro	 see Yugoslavia@"
+"Montserrat	M7@"
+"Morocco	M8@"
+"Mountain Lakes wilderness (local OSU Cutter)	M67@"
+"Mozambique	M85@"
+"Mt Hood & vicinity (local OSU Cutter)	H68@"
+"Mt Hood National Forest (local OSU Cutter)	H66@"
+"Mt Hood Wilderness (local OSU Cutter)	H67@"
+"Mt Jefferson area (local OSU Cutter)	J45@"
+"Mt Jefferson Wilderness (local OSU Cutter)	J4@"
+"Mt. Washington Wilderness (local OSU Cutter)	W38@"
+"Myanmar	 see Burma@"
+"Myrtle Creek (local OSU Cutter)	M9@"
+"Namibia	N3@"
+"Nauru	N32@"
+"Near East	 see Middle East@"
+"Nebraska	N2@"
+"Nehalem River (local OSU Cutter)	N35@"
+"Nepal	N35@"
+"Nestucca River (local OSU Cutter)	N5@"
+"Netherlands	N4@"
+"Netherlands Antilles	N42@"
+"Nevada	N3@"
+"New Brunswick	N5@"
+"New Caledonia	N425@"
+"New Guinea	N43@"
+"New Hampshire	N4@"
+"New Hebrides	 see Vanuatu@"
+"New Jersey	N5@"
+"New Mexico	.N6@"
+"New York	N7@"
+"New Zealand	N45@"
+"Newberry Crater/Volcano (local OSU Cutter)	N4@"
+"Newfoundland	N6@"
+"Newport (local OSU Cutter)	N4@"
+"Nicaragua	N5@"
+"Niger	N55@"
+"Nigeria	N6@"
+"North America	N7@"
+"North Carolina	N8@"
+"North coast drainage basin (local OSU Cutter)	N6@"
+"North Dakota	N9@"
+"North Fork John Day wilderness (local OSU Cutter)	N7@"
+"Northeast Oregon district (local OSU Cutter)	N64@"
+"Northern Ireland	 see Great Britain@"
+"Northern Rhodesia	 see Zambia@"
+"Northwest Oregon protection district (local OSU Cutter)	N61@"
+"Northwest Territories	N7@"
+"Norway	N8@"
+"Nova Scotia	N8@"
+"Nyasaland	 see Malawi@"
+"Oceania	O3@"
+"Ochoco Creek (local OSU Cutter)	O33@"
+"Ochoco National Forest (local OSU Cutter)	O34@"
+"Ohio	O3@"
+"Oklahoma	O5@"
+"Olallie Scenic Area (local OSU Cutter)	O43@"
+"Oman	O5@"
+"Ontario	O6@"
+"Oregon	O7@"
+"Oregon Caves (local OSU Cutter)	O66@"
+"Oregon City (local OSU Cutter)	O74@"
+"Oregon Dunes National Recreation Area (local OSU Cutter)	O68@"
+"Oregon Islands wilderness (local OSU Cutter)	O7@"
+"Oregon State University Campus (local OSU Cutter)	C6:2O7@"
+"Oregon Trail (local OSU Cutter)	O72@"
+"Outer Mongolia	 see Mongolia@"
+"Owyhee basin (local OSU Cutter)	O9@"
+"Pacific Area	P16@"
+"Pakistan	P18@"
+"Palau	P185@"
+"Palestine	P19@"
+"Panama	P2@"
+"Papua New Guinea	P26@"
+"Paraguay	P3@"
+"Paul Dunn forest (local OSU Cutter)	P32@"
+"Peavy arboretum (local OSU Cutter)	M2:2P4@"
+"Pennsylvania	.P4@"
+"Persia	 see Iran@"
+"Persian Gulf Region	P35@"
+"Peru	P4@"
+"Philippines	P6@"
+"Poland	P7@"
+"Pole Canyon (local OSU Cutter)	P58@"
+"Polynesia	P75@"
+"Port Orford (local OSU Cutter)	O74@"
+"Portland (local OSU Cutter)	P67@"
+"Portugal	P8@"
+"Powder drainage basin (local OSU Cutter)	P6@"
+"Powell Butte (local OSU Cutter)	P62@"
+"Prince Edward Island	P8@"
+"Prineville (local OSU Cutter)	P74@"
+"Prussia	 see Germany@"
+"Prussia, East (Poland and Russia)	P85@"
+"Puerto Rico	P9@"
+"Qatar	Q2@"
+"Quartzville Mining District (local OSU Cutter)	Q3@"
+"Quebec (Province)	Q3@"
+"Rastus Mountain (local OSU Cutter)	R3@"
+"Red Buttes Wilderness (local OSU Cutter)	R44@"
+"Reunion	R4@"
+"Rhode Island	R4@"
+"Rhodesia, Northern	 see Zambia@"
+"Rhodesia, Southern	 see Zimbabwe@"
+"Rogue River National Forest (local OSU Cutter)	R64@"
+"Rogue River (local OSU Cutter)	R6@"
+"Rogue-Umpqua Divide Wilderness (local OSU Cutter)	R645@"
+"Roman Empire	R57@"
+"Romania	R6@"
+"Roseburg district (BLM) (local OSU Cutter)	R66@"
+"Roseburg (local OSU Cutter)	R6@"
+"Round Mtn. (local OSU Cutter)	R68@"
+"Rumania	 see Romania@"
+"Russia	R8@"
+"Russia (Federation)	 see Russia@"
+"Rwanda	R95@"
+"Sahel	S15@"
+"Saint Kitts-Nevis	S16@"
+"Saint Lucia	S17@"
+"Saint Vincent	S18@"
+"Salem (local OSU Cutter)	S3@"
+"Salvador	S2@"
+"Samoan Islands	S24@"
+"San Marino	S27@"
+"Sandy River (local OSU Cutter)	S25@"
+"Santiam Pass (local OSU Cutter)	S3@"
+"Sao Tome and Principe	S3@"
+"Saskatchewan	S2@"
+"Saudi Arabia	S33@"
+"Sawtooth Ridge (local OSU Cutter)	S2@"
+"Scandinavia	S34@"
+"Scotland	 see Great Britain@"
+"Senegal	S38@"
+"Serbia	 see Yugoslavia@"
+"Seychelles	S45@"
+"Siam	 see Thailand@"
+"Siberia	 see Russia@"
+"Sierra Leone	S5@"
+"Siletz River (local OSU Cutter)	S5@"
+"Siltcoos Lake (local OSU Cutter)	S52@"
+"Silver Creek Falls State Park (local OSU Cutter)	S54@"
+"Singapore	S55@"
+"Siskiyou National Forest (local OSU Cutter)	S57@"
+"Siuslaw National Forest (local OSU Cutter)	S59@"
+"Sky Lakes (local OSU Cutter)	S6@"
+"Slovakia	S56@"
+"Slovenia	S57@"
+"Solomon Islands	S575@"
+"Somalia	S58@"
+"South Africa	S6@"
+"South America	S63@"
+"South Asia	S64@"
+"South Carolina	S6@"
+"South coast basin (local OSU Cutter)	S63@"
+"South Dakota	S8@"
+"Southeast Oregon (local OSU Cutter)	S64@"
+"Southern Cone of South America,	 see South America@"
+"Southwest Oregon (local OSU Cutter)	S65@"
+"Soviet Union	S65@"
+"Spain	S7@"
+"Sri Lanka	S72@"
+"St. Helens (local OSU Cutter)	S2@"
+"Steens Mountain (local OSU Cutter)	S7@"
+"Strawberry Mountain (local OSU Cutter)	S75@"
+"Sudan	S73@"
+"Sudan (Region)	S74@"
+"Sunriver (local OSU Cutter)	S87@"
+"Suplee-Izee area (local OSU Cutter)	S9@"
+"Surinam	S75@"
+"Swaziland	S78@"
+"Sweden	S8@"
+"Switzerland	S9@"
+"Syria	S95@"
+"Taiwan	T28@"
+"Tajikistan	T3@"
+"Tamil Nadu	 see India@"
+"Tanganyika	 see Tanzania@"
+"Tanzania	T34@"
+"Tasmania	 see Australia@"
+"Tennessee	T2@"
+"Terres australes et antarctiques françaises	T47@"
+"Texas	T4@"
+"Thailand	T5@"
+"Three Sisters Wilderness (local OSU Cutter)	T47@"
+"Three Sisters (local OSU Cutter)	T45@"
+"Tibet	T55@"
+"Tillamook Burn (local OSU Cutter)	T54@"
+"Tillamook district (local OSU Cutter)	N61:3T5@"
+"Tobago	 see Trinidad and Tobago@"
+"Togo	T6@"
+"Tonga	T63@"
+"Transvaal	 see South Africa@"
+"Trinidad and Tobago	T7@"
+"Trinidad	 see Trinidad and Tobago@"
+"Tropics	T73@"
+"Tualatin Valley (local OSU Cutter)	T83@"
+"Tubuai Islands	T77@"
+"Tunisia	T8@"
+"Turkey	T9@"
+"Turkmenistan	T93@"
+"Turks and Caicos Islands	T94@"
+"Tuvalu	T95@"
+"Uganda	U33@"
+"Ukraine	U38@"
+"Umatilla basin (local OSU Cutter)	U41@"
+"Umatilla National Forest (local OSU Cutter)	U43@"
+"Umpqua drainage basin (local OSU Cutter)	U46@"
+"Umpqua National Forest (local OSU Cutter)	U463@"
+"United Arab Emirates	U5@"
+"United States	U6@"
+"University of Oregon Campus (local OSU Cutter)	E8:2U5@"
+"Upper coast drainage basin (local OSU Cutter)	U6@"
+"Upper Volta	 see Burkina Faso@"
+"Upper Willamette drainage basin (local OSU Cutter)	W52@"
+"Uruguay	U8@"
+"Utah	U8@"
+"Uzbekistan	U9@"
+"Vale district (BLM) (local OSU Cutter)	V3@"
+"Vanuatu	V26@"
+"Vatican City	V3@"
+"Venezuela	V4@"
+"Vermont	V5@"
+"Vietnam	V5@"
+"Vietnam (Democratic Republic)	 see Vietnam@"
+"Virgin Islands	V6@"
+"Virgin Islands of the United States	V63@"
+"Virginia	V8@"
+"Virtue Flatt (local OSU Cutter)	V5@"
+"Waldo Lake (local OSU Cutter)	W33@"
+"Waldport (local OSU Cutter)	W18@"
+"Wales	 see Great Britain@"
+"Wallowa-Whitman National Forest (local OSU Cutter)	W34@"
+"Warm Springs Indian Reservation (local OSU Cutter)	W37@"
+"Washington (D.C.)	W18@"
+"Washington (State)	W2@"
+"Wenaha-Tucannon Wilderness (local OSU Cutter)	W43@"
+"West Indies, British	W47@"
+"West Indies, French	W48@"
+"West Linn (local OSU Cutter)	W45@"
+"West Virginia	W4@"
+"Western Australia	 see Australia@"
+"Western Oregon (local OSU Cutter)	W4@"
+"Western Samoa	W5@"
+"Whitehorse Caldera (local OSU Cutter)	W48@"
+"Willamette National Forest (local OSU Cutter)	W51@"
+"Willamette River (local OSU Cutter)	W5@"
+"Wilson River (local OSU Cutter)	W542@"
+"Winema National Forest (local OSU Cutter)	W545@"
+"Wisconsin	W6@"
+"Wyoming	W8@"
+"Yaquina Bay (local OSU Cutter)	Y3@"
+"Yemen	Y4@"
+"Yemen (People's Democratic Republic)	 see Yemen@"
+"Yugoslavia	Y8@"
+"Yukon (Territory)	Y8@"
+"Zaire	Z28@"
+"Zambezi River Region	Z32@"
+"Zambia	Z33@"
+"Zimbabwe	Z55";
