var lang="aar	Afar@"
+"abk	Abkhaz@"
+"ace	Achinese@"
+"ach	Acoli@"
+"ady	Adangme@"
+"ada	Adygei@"
+"afh	Afrihili (Artificial language)@"
+"afr	Afrikaans@"
+"afa	Afroasiatic (Other)@"
+"aka	Akan@"
+"akk	Akkadian@"
+"alb	Albanian@"
+"ale	Aleut@"
+"alg	Algonquian (Other)@"
+"[discontinued code] ajm	Aljamía@"
+"tut	Altaic (Other)@"
+"amh	Amharic@"
+"apa	Apache languages@"
+"ara	Arabic@"
+"arg	Aragonese Spanish@"
+"arc	Aramaic@"
+"arp	Arapaho@"
+"arw	Arawak@"
+"arm	Armenian@"
+"art	Artificial (Other)@"
+"asm	Assamese@"
+"ath	Athapascan (Other)@"
+"aus	Australian languages@"
+"map	Austronesian (Other)@"
+"ava	Avaric@"
+"ave	Avestan@"
+"nic	Avikam@"
+"awa	Awadhi@"
+"nic 	Awutu@"
+"aym	Aymara@"
+"aze	Azerbaijani@"
+"ast	Bable@"
+"ban	Balinese@"
+"bat	Baltic (Other)@"
+"bal	Baluchi@"
+"bam	Bambara@"
+"bai	Bamileke languages@"
+"bad	Banda@"
+"bnt	Bantu (Other)@"
+"bas	Basa@"
+"bak	Bashkir@"
+"baq	Basque@"
+"btk	Batak@"
+"bej	Beja@"
+"bel	Belarusian@"
+"bem	Bemba@"
+"ben	Bengali@"
+"ber	Berber (Other)@"
+"bho	Bhojpuri@"
+"bih	Bihari@"
+"bik	Bikol@"
+"paa	Bimin@"
+"bis	Bislama@"
+"bos	Bosnian@"
+"bra	Braj@"
+"bre	Breton@"
+"bug	Bugis@"
+"bul	Bulgarian@"
+"bua	Buriat@"
+"bur	Burmese@"
+"cad	Caddo@"
+"car	Carib@"
+"cat	Catalan@"
+"cau	Caucasian (Other)@"
+"ceb	Cebuano@"
+"cel	Celtic (Other)@"
+"cai	Central American Indian (Other)@"
+"chg	Chagatai@"
+"cmc	Chamic languages@"
+"cha	Chamorro@"
+"che	Chechen@"
+"chr	Cherokee@"
+"chy	Cheyenne@"
+"chb	Chibcha@"
+"nai 	Chimariko@"
+"chi	Chinese@"
+"chn	Chinook jargon@"
+"chp	Chipewyan@"
+"cho	Choctaw@"
+"chu	Church Slavic@"
+"chv	Chuvash@"
+"cop	Coptic@"
+"cor	Cornish@"
+"cos	Corsican@"
+"cre	Cree@"
+"mus	Creek@"
+"crp	Creoles and Pidgins (Other)@"
+"cpe	Creoles and Pidgins, English-based (Other)@"
+"cpf	Creoles and Pidgins, French-based (Other)@"
+"cpp	Creoles and Pidgins, Portuguese-based (Other)@"
+"crh	Crimean Tatar@"
+"hrv	Croatian@"
+"[discontinued code] scr	Croatian@"
+"cus	Cushitic (Other)@"
+"cze	Czech@"
+"dak	Dakota@"
+"dan	Danish@"
+"dar	Dargwa@"
+"day	Dayak@"
+"del	Delaware@"
+"din	Dinka@"
+"bnt	Diriku@"
+"div	Divehi@"
+"doi	Dogri@"
+"dgr	Dogrib@"
+"dra	Dravidian (Other)@"
+"dua	Duala@"
+"dum	Dutch, Middle (ca. 1050-1350)@"
+"dut	Dutch@"
+"dyu	Dyula@"
+"dzo	Dzongkha@"
+"bin	Edo@"
+"efi	Efik@"
+"nic 	Eggon@"
+"egy	Egyptian@"
+"eka	Ekajuk@"
+"elx	Elamite@"
+"enm	English, Middle (1100-1500)@"
+"ang	English, Old (ca. 450-1100)@"
+"eng	English@"
+"[discontinued code] esk	Eskimo languages@"
+"[discontinued code] esp	Esperanto@"
+"epo	Esperanto@"
+"est	Estonian@"
+"[discontinued code] eth	Ethiopic@"
+"gez	Ethiopic@"
+"ewe	Ewe@"
+"ewo	Ewondo@"
+"fan	Fang@"
+"fat	Fanti@"
+"[discontinued code] far	Faroese@"
+"fao	Faroese@"
+"fij	Fijian@"
+"fin	Finnish@"
+"fiu	Finno-Ugrian (Other)@"
+"fon	Fon@"
+"frm	French, Middle (ca. 1400-1600)@"
+"fro	French, Old (ca. 842-1400)@"
+"fre	French@"
+"[discontinued code] fri	Frisian@"
+"fry	Frisian@"
+"fur	Friulian@"
+"ful	Fula@"
+"gaa	Gã@"
+"[discontinued code] gag	Galician@"
+"glg	Galician@"
+"lug	Ganda@"
+"gay	Gayo@"
+"gba	Gbaya@"
+"geo	Georgian@"
+"gmh	German, Middle High (ca. 1050-1500)@"
+"goh	German, Old High (ca. 750-1050)@"
+"ger	German@"
+"nds	Germanic (Other)@"
+"gil	Gilbertese@"
+"gon	Gondi@"
+"gor	Gorontalo@"
+"got	Gothic@"
+"grb	Grebo@"
+"grc	Greek, Ancient (to 1453)@"
+"gre	Greek, Modern (1453- )@"
+"gsw	Swiss German@"
+"[discontinued code] gua	Guarani@"
+"grn	Guarani@"
+"guj	Gujarati@"
+"aus	Gunian@"
+"paa	Gwahatike@"
+"gwi	Gwich'in@"
+"bnt	Ha@"
+"hai	Haida@"
+"hat	Haitian French Creole@"
+"hau	Hausa@"
+"haw	Hawaiian@"
+"heb	Hebrew@"
+"afa	Hedi@"
+"her	Herero@"
+"hil	Hiligaynon@"
+"him	Himachali@"
+"hin	Hindi@"
+"hmo	Hiri Motu@"
+"hit	Hittite@"
+"hmn	Hmong@"
+"map	Hote@"
+"hun	Hungarian@"
+"hup	Hupa@"
+"iba	Iban@"
+"ice	Icelandic@"
+"ido	Ido@"
+"ibo	Igbo@"
+"ijo	Ijo@"
+"ilo	Iloko@"
+"smn	Inari Sami@"
+"inc	Indic (Other)@"
+"ine	Indo-European (Other)@"
+"ind	Indonesian@"
+"inh	Ingush@"
+"[discontinued code] int	Interlingua (International Auxiliary Language Association)@"
+"ina	Interlingua (International Auxiliary Language Association)@"
+"ile	Interlingue@"
+"iku	Inuktitut@"
+"ipk	Inupiaq@"
+"ira	Iranian (Other)@"
+"mga	Irish, Middle (ca. 1100-1550)@"
+"sga	Irish, Old (to 1100)@"
+"[discontinued code] iri	Irish@"
+"gle	Irish@"
+"iro	Iroquoian (Other)@"
+"ita	Italian@"
+"jpn	Japanese@"
+"jav	Javanese@"
+"jrb	Judeo-Arabic@"
+"jpr	Judeo-Persian@"
+"ssa	Kaba (Central Sudanic)@"
+"kbd	Kabardian@"
+"kab	Kabyle@"
+"kac	Kachin@"
+"nic	Kagoro (Mali)@"
+"kal	Kalatdlisut@"
+"xal	Kalmyk@"
+"kam	Kamba@"
+"kan	Kannada@"
+"kau	Kanuri@"
+"kaa	Kara-Kalpak@"
+"krc	Karachay-Balkar@"
+"kar	Karen@"
+"kas	Kashmiri@"
+"kaw	Kawi@"
+"map	Kayan@"
+"kaz	Kazakh@"
+"kha	Khasi@"
+"[discontinued code] cam	Khmer@"
+"khm	Khmer@"
+"khi	Khoisan (Other)@"
+"kho	Khotanese@"
+"kik	Kikuyu@"
+"kmb	Kimbundu@"
+"kin	Kinyarwanda@"
+"kom	Komi@"
+"kon	Kongo@"
+"kok	Konkani@"
+"nic 	Konni@"
+"kor	Korean@"
+"kpe	Kpelle@"
+"kro	Kru@"
+"kua	Kuanyama@"
+"kum	Kumyk@"
+"kur	Kurdish@"
+"kru	Kurukh@"
+"[discontinued code] kus	Kusaie@"
+"kos	Kusaie@"
+"kut	Kutenai@"
+"kir	Kyrgyz@"
+"lad	Ladino@"
+"lah	Lahnda@"
+"lam	Lamba@"
+"lao	Lao@"
+"lat	Latin@"
+"lav	Latvian@"
+"ltz	Letzeburgesch@"
+"lez	Lezgian@"
+"lim	Limburgish@"
+"lin	Lingala@"
+"lit	Lithuanian@"
+"nds	Low German@"
+"loz	Lozi@"
+"lub	Luba-Katanga@"
+"lua	Luba-Lulua@"
+"lui	Luiseño@"
+"smj	Lule Sami@"
+"lun	Lunda@"
+"luo	Luo (Kenya and Tanzania)@"
+"lus	Lushai@"
+"mac	Macedonian@"
+"mad	Madurese@"
+"mag	Magahi@"
+"mai	Maithili@"
+"mak	Makasar@"
+"[discontinued code] mla	Malagasy@"
+"mlg	Malagasy@"
+"may	Malay@"
+"mal	Malayalam@"
+"afa	Male (Ethiopia)@"
+"mlt	Maltese@"
+"mnc	Manchu@"
+"mdr	Mandar@"
+"man	Mandingo@"
+"mni	Manipuri@"
+"mno	Manobo languages@"
+"[discontinued code] max	Manx@"
+"glv	Manx@"
+"mao	Maori@"
+"arn	Mapuche@"
+"mar	Marathi@"
+"chm	Mari@"
+"mah	Marshallese@"
+"mwr	Marwari@"
+"mas	Masai@"
+"myn	Mayan languages@"
+"bnt	Mbunda (Angola and Zambia)@"
+"men	Mende@"
+"mic	Micmac@"
+"min	Minangkabau@"
+"mis	Miscellaneous languages@"
+"moh	Mohawk@"
+"rum	Moldavan@"
+"[discontinued code] mol	Moldovian@"
+"mon	Mongolian@"
+"lol	Mongo-Nkundu@"
+"mkh	Mon-Khmer (Other)@"
+"mos	Mooré@"
+"mul	Multiple languages@"
+"mun	Munda (Other)@"
+"nah	Nahuatl@"
+"nau	Nauru@"
+"nav	Navajo@"
+"bnt	Ndau@"
+"nbl	Ndebele (South Africa)@"
+"nde	Ndebele (Zimbabwe)@"
+"ndo	Ndonga@"
+"nap	Neapolitan Italian@"
+"nep	Nepali@"
+"new	Newari@"
+"nia	Nias@"
+"nic	Niger-Kordofanian (Other)@"
+"ssa	Nilo-Saharan (Other)@"
+"niu	Niuean@"
+"nog	Nogai@"
+"nai	North American Indian (Other)@"
+"sme	Northern Sami@"
+"nso	Northern Sotho@"
+"nno	Norwegian (Nynorsk)@"
+"nor	Norwegian@"
+"nub	Nubian languages@"
+"nym	Nyamwezi@"
+"nya	Nyanja@"
+"nyn	Nyankole@"
+"nyo	Nyoro@"
+"nzi	Nzima@"
+"[discontinued code] lan	Occitan (post-1500)@"
+"oci	Occitan (post-1500)@"
+"nic	Ogbronuagum@"
+"oji	Ojibwa@"
+"non	Old Norse@"
+"nob	Old Norwegian (Bokmål)@"
+"peo	Old Persian (ca. 600-400 B.C.)@"
+"ori	Oriya@"
+"orm	Orma@"
+"tut	Oroch@"
+"[discontinued code] gal	Oromo@"
+"orm	Oromo@"
+"osa	Osage@"
+"oss	Ossetic@"
+"oto	Otomian languages@"
+"pal	Pahlavi@"
+"pau	Palauan@"
+"pli	Pali@"
+"pam	Pampanga@"
+"pag	Pangasinan@"
+"pan	Panjabi@"
+"pap	Papiamento@"
+"paa	Papuan (Other)@"
+"per	Persian@"
+"phi	Philippine (Other)@"
+"phn	Phoenician@"
+"bnt	Pokomo@"
+"pol	Polish@"
+"pon	Ponape@"
+"por	Portuguese@"
+"pra	Prakrit languages@"
+"pro	Provençal (to 1500)@"
+"pus	Pushto@"
+"que	Quechua@"
+"roh	Raeto-Romance@"
+"raj	Rajasthani@"
+"rap	Rapanui@"
+"rar	Rarotongan@"
+"roa	Romance (Other)@"
+"rom	Romani@"
+"rum	Romanian@"
+"run	Rundi@"
+"rus	Russian@"
+"sal	Salishan languages@"
+"sam	Samaritan Aramaic@"
+"[discontinued code] lap	Sami@"
+"smi	Sami@"
+"[discontinued code] sao	Samoan@"
+"smo	Samoan@"
+"sad	Sandawe@"
+"sag	Sango (Ubangi Creole)@"
+"san	Sanskrit@"
+"sat	Santali@"
+"srd	Sardinian@"
+"sas	Sasak@"
+"sco	Scots@"
+"[discontinued code] gae	Scottish Gaelic@"
+"gla	Scottish Gaelic@"
+"sel	Selkup@"
+"sem	Semitic (Other)@"
+"nic	Senya@"
+"srp	Serbian@"
+"[discontinued code] scc	Serbian@"
+"srr	Serer@"
+"shn	Shan@"
+"[discontinued code] sho	Shona@"
+"sna	Shona@"
+"iii	Sichuan Yi@"
+"sid	Sidamo@"
+"sgn	Sign languages@"
+"bla	Siksika@"
+"snd	Sindhi@"
+"[discontinued code] snh	Sinhalese@"
+"sin	Sinhalese@"
+"sit	Sino-Tibetan (Other)@"
+"sio	Siouan (Other)@"
+"sms	Skolt Sami@"
+"den	Slave@"
+"sla	Slavic (Other)@"
+"slo	Slovak@"
+"slv	Slovenian@"
+"sog	Sogdian@"
+"som	Somali@"
+"son	Songhai@"
+"snk	Soninke@"
+"wen	Sorbian languages@"
+"[discontinued code] sso	Sotho@"
+"sot	Sotho@"
+"sai	South American Indian (Other)@"
+"sma	Southern Sami@"
+"ath	Southern Tutchone@"
+"spa	Spanish@"
+"suk	Sukuma@"
+"sux	Sumerian@"
+"sun	Sundanese@"
+"sus	Susu@"
+"swa	Swahili@"
+"[discontinued code] swz	Swazi@"
+"ssw	Swazi@"
+"swe	Swedish@"
+"syr	Syriac@"
+"[discontinued code] tag	Tagalog@"
+"tgl	Tagalog@"
+"tah	Tahitian@"
+"tai	Tai (Other)@"
+"[discontinued code] taj	Tajik@"
+"tgk	Tajik@"
+"bnt	Talinga-Bwisi@"
+"tmh	Tamashek@"
+"tam	Tamil@"
+"sai	Tariana@"
+"[discontinued code] tar	Tatar@"
+"tat	Tatar@"
+"tel	Telugu@"
+"tem	Temne@"
+"ter	Terena@"
+"tet	Tetum@"
+"tha	Thai@"
+"tib	Tibetan@"
+"tig	Tigré@"
+"tir	Tigrinya@"
+"tiv	Tiv@"
+"tli	Tlingit@"
+"tpi	Tok Pisin@"
+"tkl	Tokelauan@"
+"tog	Tonga (Nyasa)@"
+"ton	Tongan@"
+"sai	Trio@"
+"[discontinued code] tru	Truk@"
+"chk	Truk@"
+"tsi	Tsimshian@"
+"tso	Tsonga@"
+"[discontinued code] tsw	Tswana@"
+"tsn	Tswana@"
+"tum	Tumbuka@"
+"tup	Tupi languages@"
+"ota	Turkish, Ottoman@"
+"tur	Turkish@"
+"tuk	Turkmen@"
+"tvl	Tuvaluan@"
+"tyv	Tuvinian@"
+"twi	Twi@"
+"udm	Udmurt@"
+"uga	Ugaritic@"
+"uig	Uighur@"
+"ukr	Ukrainian@"
+"umb	Umbundu@"
+"und	Undetermined@"
+"urd	Urdu@"
+"uzb	Uzbek@"
+"vai	Vai@"
+"art	Vela (Artificial language)@"
+"ven	Venda@"
+"vie	Vietnamese@"
+"vol	Volapük@"
+"vot	Votic@"
+"wak	Wakashan languages@"
+"wal	Walamo@"
+"wln	Walloon@"
+"war	Waray@"
+"was	Washo@"
+"wel	Welsh@"
+"wol	Wolof@"
+"xho	Xhosa@"
+"sah	Yakut@"
+"yao	Yao (Africa)@"
+"yap	Yapese@"
+"yid	Yiddish@"
+"yor	Yoruba@"
+"aus	Yugumbir@"
+"ypk	Yupik languages@"
+"alg	Yurok@"
+"znd	Zande@"
+"zap	Zapotec@"
+"zen	Zenaga@"
+"zha	Zhuang@"
+"zul	Zulu@"
+"zun	Zuni@"
+"sem	Zway@";
