var rdacontent="cartographic dataset	crd@"
+"cartographic image	cri@"
+"cartographic moving image	crm@"
+"cartographic tactile image	crt@"
+"cartographic tactile three-dimensional form	crn@"
+"cartographic three-dimensional form	crf@"
+"computer dataset	cod@"
+"computer program	cop@"
+"notated movement	ntv@"
+"notated music	ntm@"
+"performed music	prm@"
+"sounds	snd@"
+"spoken word	spw@"
+"still image	sti@"
+"tactile image	tci@"
+"tactile notated music	tcm@"
+"tactile notated movement	tcn@"
+"tactile text	tct@"
+"tactile three-dimensional form	tcf@"
+"text	txt@"
+"three-dimensional form	tdf@"
+"three-dimensional moving image	tdm@"
+"two-dimensional moving image	tdi@"
+"other	xxx@"
+"unspecified	zzz";
